/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.inv;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDate;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 */
@SuppressWarnings("serial")
public class InvoiceVO extends SuperVO {
	private String pk_corp;
	private UFDateTime create_time;
	private String cust_orderno;
	private Integer vbillstatus;
	private UFDateTime order_time;
	private Integer dr;
	private Integer invoice_origin;
	private String bala_customer;
	private String returnbill_no;
	private String pk_arrival;
	private UFDateTime ts;
	private String cost_center;
	private String feature;
	private String trade_term;
	private UFBoolean if_ins_receipt;
	private UFBoolean if_customs_official;
	private String pk_trans_type;
	private String pk_dept;
	private String create_user;
	private UFBoolean if_insurance;
	private UFBoolean if_billing;
	private String contact;
	private String pk_service_type;
	private UFDouble volume_count;
	private String vbillno;
	private UFDouble fee_weight_count;
	private String req_deli_time;
	private String pk_psndoc;
	private String req_arri_date;
	private String pk_customer;
	private UFDouble insurance_amount;
	private UFBoolean if_return;
	private Integer balatype;
	private Integer urgent_level;
	private String pk_carrier;
	private String arri_process;
	private String req_arri_time;
	private UFDouble distance;
	private String memo;
	private String pk_invoice_type;
	private String req_deli_date;
	private UFDouble weight_count;
	private UFDouble receipt_amount;
	private String note;
	private UFDouble amount;
	private UFDouble cost_amount;
	private String pk_delivery;
	private String pk_invoice;
	private UFDouble pack_num_count;
	private Integer num_count;
	private String deli_process;
	private Integer mileage;
	private UFBoolean if_backbill;
	private Integer backbill_num;
	private String insurance_no;
	private String orderno;
	private String customs_official_no;
	private String deli_city;
	private String deli_province;
	private String deli_area;
	private String deli_detail_addr;
	private String deli_contact;
	private String deli_mobile;
	private String deli_phone;
	private String deli_email;
	private String arri_city;
	private String arri_province;
	private String arri_area;
	private String arri_detail_addr;
	private String arri_contact;
	private String arri_mobile;
	private String arri_phone;
	private String arri_email;
	private UFDouble volume_weight_count;
	private Integer deli_method;
	private UFDouble arri_pay_amount;

	private UFDateTime tracking_time;
	private Integer tracking_status;
	private String tracking_memo;
	private UFBoolean exp_flag;
	private String exp_type;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;

	private UFDate dbilldate;
	private String modify_user;
	private UFDateTime modify_time;

	// 2015-05-24
	private String act_deli_date;
	private String act_arri_date;
	private String con_arri_date;
	private String item_code;// 项目号
	private String item_name;// 项目名称
	//yaojiie 2015 12 08 将unconfirm_type更改为Integer
	private Integer unconfirm_type;
	private String unconfirm_memo;
	
	//2015-11-10 增加确认人，确认时间，反确认人，反确认时间 Jonathan
	private String confirm_date;
	private String confirm_user;
	private String unconfirm_date;
	private String unconfirm_user;
	private String invoice_goods_type;
	private String pk_supplier;//供应商
	
	// 2015-5-30
	private String cs_req_deli_date;// 客服要求提货日期
	//yaojiie 2016 1 11 线路字段
	private String pk_trans_line;
	private UFBoolean kpi_flag;
	
	private String urgent_reson;
	private String cargo_flow;
	private String supervision_type;
	private String vehicle_req;
	private String transport_req;
	private String other_req;
	private String currency;
	
	private String pz_line;
	private Integer pz_mileage;
	
	
	private Integer trans_type;//运输类型
	
	private String pk_op_project;
	private String billing_corp;
	
	
	public String getPk_op_project() {
		return pk_op_project;
	}

	public void setPk_op_project(String pk_op_project) {
		this.pk_op_project = pk_op_project;
	}

	public String getBilling_corp() {
		return billing_corp;
	}

	public void setBilling_corp(String billing_corp) {
		this.billing_corp = billing_corp;
	}

	public Integer getTrans_type() {
		return trans_type;
	}

	public void setTrans_type(Integer trans_type) {
		this.trans_type = trans_type;
	}

	public String getPz_line() {
		return pz_line;
	}

	public void setPz_line(String pz_line) {
		this.pz_line = pz_line;
	}

	public Integer getPz_mileage() {
		return pz_mileage;
	}

	public void setPz_mileage(Integer pz_mileage) {
		this.pz_mileage = pz_mileage;
	}

	public String getUrgent_reson() {
		return urgent_reson;
	}

	public void setUrgent_reson(String urgent_reson) {
		this.urgent_reson = urgent_reson;
	}

	public String getCargo_flow() {
		return cargo_flow;
	}

	public void setCargo_flow(String cargo_flow) {
		this.cargo_flow = cargo_flow;
	}

	public String getSupervision_type() {
		return supervision_type;
	}

	public void setSupervision_type(String supervision_type) {
		this.supervision_type = supervision_type;
	}

	public String getVehicle_req() {
		return vehicle_req;
	}

	public void setVehicle_req(String vehicle_req) {
		this.vehicle_req = vehicle_req;
	}

	public String getTransport_req() {
		return transport_req;
	}

	public void setTransport_req(String transport_req) {
		this.transport_req = transport_req;
	}

	public String getOther_req() {
		return other_req;
	}

	public void setOther_req(String other_req) {
		this.other_req = other_req;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getInvoice_goods_type() {
		return invoice_goods_type;
	}

	public void setInvoice_goods_type(String invoice_goods_type) {
		this.invoice_goods_type = invoice_goods_type;
	}

	public UFBoolean getKpi_flag() {
		return kpi_flag;
	}

	public void setKpi_flag(UFBoolean kpi_flag) {
		this.kpi_flag = kpi_flag;
	}

	public String getPk_trans_line() {
		return pk_trans_line;
	}

	public void setPk_trans_line(String pk_trans_line) {
		this.pk_trans_line = pk_trans_line;
	}

	public String getCs_req_deli_date() {
		return cs_req_deli_date;
	}

	public void setCs_req_deli_date(String cs_req_deli_date) {
		this.cs_req_deli_date = cs_req_deli_date;
	}

	public String getAct_deli_date() {
		return act_deli_date;
	}

	public void setAct_deli_date(String act_deli_date) {
		this.act_deli_date = act_deli_date;
	}

	public String getAct_arri_date() {
		return act_arri_date;
	}

	public void setAct_arri_date(String act_arri_date) {
		this.act_arri_date = act_arri_date;
	}

	public String getCon_arri_date() {
		return con_arri_date;
	}

	public void setCon_arri_date(String con_arri_date) {
		this.con_arri_date = con_arri_date;
	}

	public String getItem_code() {
		return item_code;
	}

	public void setItem_code(String item_code) {
		this.item_code = item_code;
	}

	public String getItem_name() {
		return item_name;
	}

	public void setItem_name(String item_name) {
		this.item_name = item_name;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public UFDouble getPack_num_count() {
		return pack_num_count;
	}

	public void setPack_num_count(UFDouble pack_num_count) {
		this.pack_num_count = pack_num_count;
	}

	public Integer getBackbill_num() {
		return backbill_num;
	}

	public void setBackbill_num(Integer backbill_num) {
		this.backbill_num = backbill_num;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String ARRI_PAY_AMOUNT = "arri_pay_amount";
	public static final String DELI_METHOD = "deli_method";
	public static final String VOLUME_WEIGHT_COUNT = "volume_weight_count";
	public static final String PK_CORP = "pk_corp";
	public static final String CREATE_TIME = "create_time";
	public static final String CUST_ORDERNO = "cust_orderno";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String ORDER_TIME = "order_time";
	public static final String ORIGIN = "origin";
	public static final String BALA_CUSTOMER = "bala_customer";
	public static final String RETURNBILL_NO = "returnbill_no";
	public static final String PK_ARRIVAL = "pk_arrival";
	public static final String COST_CENTER = "cost_center";
	public static final String FEATURE = "feature";
	public static final String TRADE_TERM = "trade_term";
	public static final String IF_INS_RECEIPT = "if_ins_receipt";
	public static final String IF_CUSTOMS_OFFICIAL = "if_customs_official";
	public static final String PK_TRANS_TYPE = "pk_trans_type";
	public static final String PK_DEPT = "pk_dept";
	public static final String CREATE_USER = "create_user";
	public static final String IF_INSURANCE = "if_insurance";
	public static final String IF_BILLING = "if_billing";
	public static final String CONTACT = "contact";
	public static final String PK_SERVICE_TYPE = "pk_service_type";
	public static final String VOLUME_COUNT = "volume_count";
	public static final String VBILLNO = "vbillno";
	public static final String FEE_WEIGHT_COUNT = "fee_weight_count";
	public static final String REQ_DELI_TIME = "req_deli_time";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String REQ_ARRI_DATE = "req_arri_date";
	public static final String PK_CUSTOMER = "pk_customer";
	public static final String INSURANCE_AMOUNT = "insurance_amount";
	public static final String IF_RETURN = "if_return";
	public static final String BALATYPE = "balatype";
	public static final String URGENT_LEVEL = "urgent_level";
	public static final String PK_CARRIER = "pk_carrier";
	public static final String ARRI_PROCESS = "arri_process";
	public static final String REQ_ARRI_TIME = "req_arri_time";
	public static final String DISTANCE = "distance";
	public static final String MEMO = "memo";
	public static final String PK_INVOICE_TYPE = "pk_invoice_type";
	public static final String REQ_DELI_DATE = "req_deli_date";
	public static final String WEIGHT_COUNT = "weight_count";
	public static final String RECEIPT_AMOUNT = "receipt_amount";
	public static final String NOTE = "note";
	public static final String AMOUNT = "amount";
	public static final String COST_AMOUNT = "cost_amount";
	public static final String PK_DELIVERY = "pk_delivery";
	public static final String PK_INVOICE = "pk_invoice";
	public static final String NUM_COUNT = "num_count";
	public static final String DELI_PROCESS = "deli_process";
	public static final String MILEAGE = "mileage";
	public static final String IF_BACKBILL = "if_backbill";
	public static final String INSURANCE_NO = "insurance_no";
	public static final String ORDERNO = "orderno";
	public static final String CUSTOMS_OFFICIAL_NO = "customs_official_no";
	public static final String DBILLDATE = "dbilldate";
	public static final String CS_REQ_DELI_DATE = "cs_req_deli_date";

	public UFDate getDbilldate() {
		return dbilldate;
	}

	public void setDbilldate(UFDate dbilldate) {
		this.dbilldate = dbilldate;
	}

	public UFDouble getArri_pay_amount() {
		return arri_pay_amount;
	}

	public void setArri_pay_amount(UFDouble arri_pay_amount) {
		this.arri_pay_amount = arri_pay_amount;
	}

	public UFDateTime getTracking_time() {
		return tracking_time;
	}

	public void setTracking_time(UFDateTime tracking_time) {
		this.tracking_time = tracking_time;
	}

	public Integer getTracking_status() {
		return tracking_status;
	}

	public void setTracking_status(Integer tracking_status) {
		this.tracking_status = tracking_status;
	}

	public String getTracking_memo() {
		return tracking_memo;
	}

	public void setTracking_memo(String tracking_memo) {
		this.tracking_memo = tracking_memo;
	}

	public UFBoolean getExp_flag() {
		return exp_flag;
	}

	public void setExp_flag(UFBoolean exp_flag) {
		this.exp_flag = exp_flag;
	}

	public String getExp_type() {
		return exp_type;
	}

	public void setExp_type(String exp_type) {
		this.exp_type = exp_type;
	}

	public Integer getDeli_method() {
		return deli_method;
	}

	public void setDeli_method(Integer deli_method) {
		this.deli_method = deli_method;
	}

	public UFDouble getVolume_weight_count() {
		return volume_weight_count;
	}

	public void setVolume_weight_count(UFDouble volume_weight_count) {
		this.volume_weight_count = volume_weight_count;
	}

	public String getDeli_city() {
		return deli_city;
	}

	public void setDeli_city(String deli_city) {
		this.deli_city = deli_city;
	}

	public String getDeli_province() {
		return deli_province;
	}

	public void setDeli_province(String deli_province) {
		this.deli_province = deli_province;
	}

	public String getDeli_area() {
		return deli_area;
	}

	public void setDeli_area(String deli_area) {
		this.deli_area = deli_area;
	}

	public String getDeli_detail_addr() {
		return deli_detail_addr;
	}

	public void setDeli_detail_addr(String deli_detail_addr) {
		this.deli_detail_addr = deli_detail_addr;
	}

	public String getDeli_contact() {
		return deli_contact;
	}

	public void setDeli_contact(String deli_contact) {
		this.deli_contact = deli_contact;
	}

	public String getDeli_mobile() {
		return deli_mobile;
	}

	public void setDeli_mobile(String deli_mobile) {
		this.deli_mobile = deli_mobile;
	}

	public String getDeli_phone() {
		return deli_phone;
	}

	public void setDeli_phone(String deli_phone) {
		this.deli_phone = deli_phone;
	}

	public String getDeli_email() {
		return deli_email;
	}

	public void setDeli_email(String deli_email) {
		this.deli_email = deli_email;
	}

	public String getArri_city() {
		return arri_city;
	}

	public void setArri_city(String arri_city) {
		this.arri_city = arri_city;
	}

	public String getArri_province() {
		return arri_province;
	}

	public void setArri_province(String arri_province) {
		this.arri_province = arri_province;
	}

	public String getArri_area() {
		return arri_area;
	}

	public void setArri_area(String arri_area) {
		this.arri_area = arri_area;
	}

	public String getArri_detail_addr() {
		return arri_detail_addr;
	}

	public void setArri_detail_addr(String arri_detail_addr) {
		this.arri_detail_addr = arri_detail_addr;
	}

	public String getArri_contact() {
		return arri_contact;
	}

	public void setArri_contact(String arri_contact) {
		this.arri_contact = arri_contact;
	}

	public String getArri_mobile() {
		return arri_mobile;
	}

	public void setArri_mobile(String arri_mobile) {
		this.arri_mobile = arri_mobile;
	}

	public String getArri_phone() {
		return arri_phone;
	}

	public void setArri_phone(String arri_phone) {
		this.arri_phone = arri_phone;
	}

	public String getArri_email() {
		return arri_email;
	}

	public void setArri_email(String arri_email) {
		this.arri_email = arri_email;
	}

	/**
	 * ����pk_corp��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * ����pk_corp��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * ����create_time��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getCreate_time() {
		return create_time;
	}

	/**
	 * ����create_time��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newCreate_time
	 *            UFDateTime
	 */
	public void setCreate_time(UFDateTime newCreate_time) {
		this.create_time = newCreate_time;
	}

	/**
	 * ����cust_orderno��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getCust_orderno() {
		return cust_orderno;
	}

	/**
	 * ����cust_orderno��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newCust_orderno
	 *            String
	 */
	public void setCust_orderno(String newCust_orderno) {
		this.cust_orderno = newCust_orderno;
	}

	/**
	 * ����order_time��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getOrder_time() {
		return order_time;
	}

	/**
	 * ����order_time��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newOrder_time
	 *            UFDateTime
	 */
	public void setOrder_time(UFDateTime newOrder_time) {
		this.order_time = newOrder_time;
	}

	/**
	 * ����dr��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	public Integer getInvoice_origin() {
		return invoice_origin;
	}

	public void setInvoice_origin(Integer invoice_origin) {
		this.invoice_origin = invoice_origin;
	}

	/**
	 * ����bala_customer��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getBala_customer() {
		return bala_customer;
	}

	/**
	 * ����bala_customer��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newBala_customer
	 *            String
	 */
	public void setBala_customer(String newBala_customer) {
		this.bala_customer = newBala_customer;
	}

	/**
	 * ����returnbill_no��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getReturnbill_no() {
		return returnbill_no;
	}

	/**
	 * ����returnbill_no��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newReturnbill_no
	 *            String
	 */
	public void setReturnbill_no(String newReturnbill_no) {
		this.returnbill_no = newReturnbill_no;
	}

	/**
	 * ����pk_arrival��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_arrival() {
		return pk_arrival;
	}

	/**
	 * ����pk_arrival��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_arrival
	 *            String
	 */
	public void setPk_arrival(String newPk_arrival) {
		this.pk_arrival = newPk_arrival;
	}

	/**
	 * ����ts��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����cost_center��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getCost_center() {
		return cost_center;
	}

	/**
	 * ����cost_center��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newCost_center
	 *            String
	 */
	public void setCost_center(String newCost_center) {
		this.cost_center = newCost_center;
	}

	/**
	 * ����feature��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getFeature() {
		return feature;
	}

	/**
	 * ����feature��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newFeature
	 *            String
	 */
	public void setFeature(String newFeature) {
		this.feature = newFeature;
	}

	/**
	 * ����trade_term��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getTrade_term() {
		return trade_term;
	}

	/**
	 * ����trade_term��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newTrade_term
	 *            String
	 */
	public void setTrade_term(String newTrade_term) {
		this.trade_term = newTrade_term;
	}

	/**
	 * ����if_ins_receipt��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIf_ins_receipt() {
		return if_ins_receipt;
	}

	/**
	 * ����if_ins_receipt��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newIf_ins_receipt
	 *            UFBoolean
	 */
	public void setIf_ins_receipt(UFBoolean newIf_ins_receipt) {
		this.if_ins_receipt = newIf_ins_receipt;
	}

	/**
	 * ����if_customs_official��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIf_customs_official() {
		return if_customs_official;
	}

	/**
	 * ����if_customs_official��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newIf_customs_official
	 *            UFBoolean
	 */
	public void setIf_customs_official(UFBoolean newIf_customs_official) {
		this.if_customs_official = newIf_customs_official;
	}

	/**
	 * ����pk_trans_type��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_trans_type() {
		return pk_trans_type;
	}

	/**
	 * ����pk_trans_type��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_trans_type
	 *            String
	 */
	public void setPk_trans_type(String newPk_trans_type) {
		this.pk_trans_type = newPk_trans_type;
	}

	/**
	 * ����pk_dept��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_dept() {
		return pk_dept;
	}

	/**
	 * ����pk_dept��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_dept
	 *            String
	 */
	public void setPk_dept(String newPk_dept) {
		this.pk_dept = newPk_dept;
	}

	/**
	 * ����create_user��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getCreate_user() {
		return create_user;
	}

	/**
	 * ����create_user��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newCreate_user
	 *            String
	 */
	public void setCreate_user(String newCreate_user) {
		this.create_user = newCreate_user;
	}

	/**
	 * ����if_insurance��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIf_insurance() {
		return if_insurance;
	}

	/**
	 * ����if_insurance��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newIf_insurance
	 *            UFBoolean
	 */
	public void setIf_insurance(UFBoolean newIf_insurance) {
		this.if_insurance = newIf_insurance;
	}

	/**
	 * ����if_billing��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIf_billing() {
		return if_billing;
	}

	/**
	 * ����if_billing��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newIf_billing
	 *            UFBoolean
	 */
	public void setIf_billing(UFBoolean newIf_billing) {
		this.if_billing = newIf_billing;
	}

	/**
	 * ����contact��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * ����contact��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newContact
	 *            String
	 */
	public void setContact(String newContact) {
		this.contact = newContact;
	}

	/**
	 * ����pk_service_type��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_service_type() {
		return pk_service_type;
	}

	/**
	 * ����pk_service_type��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_service_type
	 *            String
	 */
	public void setPk_service_type(String newPk_service_type) {
		this.pk_service_type = newPk_service_type;
	}

	/**
	 * ����volume_count��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDouble
	 */
	public UFDouble getVolume_count() {
		return volume_count;
	}

	/**
	 * ����volume_count��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newVolume_count
	 *            UFDouble
	 */
	public void setVolume_count(UFDouble newVolume_count) {
		this.volume_count = newVolume_count;
	}

	public Integer getVbillstatus() {
		return vbillstatus;
	}

	public void setVbillstatus(Integer vbillstatus) {
		this.vbillstatus = vbillstatus;
	}

	public String getVbillno() {
		return vbillno;
	}

	public void setVbillno(String vbillno) {
		this.vbillno = vbillno;
	}

	/**
	 * ����fee_weight_count��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDouble
	 */
	public UFDouble getFee_weight_count() {
		return fee_weight_count;
	}

	/**
	 * ����fee_weight_count��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newFee_weight_count
	 *            UFDouble
	 */
	public void setFee_weight_count(UFDouble newFee_weight_count) {
		this.fee_weight_count = newFee_weight_count;
	}

	/**
	 * ����req_deli_time��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getReq_deli_time() {
		return req_deli_time;
	}

	/**
	 * ����req_deli_time��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newReq_deli_time
	 *            String
	 */
	public void setReq_deli_time(String newReq_deli_time) {
		this.req_deli_time = newReq_deli_time;
	}

	/**
	 * ����pk_psndoc��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_psndoc() {
		return pk_psndoc;
	}

	/**
	 * ����pk_psndoc��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_psndoc
	 *            String
	 */
	public void setPk_psndoc(String newPk_psndoc) {
		this.pk_psndoc = newPk_psndoc;
	}

	/**
	 * ����pk_customer��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_customer() {
		return pk_customer;
	}

	/**
	 * ����pk_customer��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_customer
	 *            String
	 */
	public void setPk_customer(String newPk_customer) {
		this.pk_customer = newPk_customer;
	}

	/**
	 * ����insurance_amount��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInsurance_amount() {
		return insurance_amount;
	}

	/**
	 * ����insurance_amount��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newInsurance_amount
	 *            UFDouble
	 */
	public void setInsurance_amount(UFDouble newInsurance_amount) {
		this.insurance_amount = newInsurance_amount;
	}

	/**
	 * ����if_return��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIf_return() {
		return if_return;
	}

	/**
	 * ����if_return��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newIf_return
	 *            UFBoolean
	 */
	public void setIf_return(UFBoolean newIf_return) {
		this.if_return = newIf_return;
	}

	public Integer getBalatype() {
		return balatype;
	}

	public void setBalatype(Integer balatype) {
		this.balatype = balatype;
	}

	/**
	 * ����urgent_level��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return Integer
	 */
	public Integer getUrgent_level() {
		return urgent_level;
	}

	/**
	 * ����urgent_level��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newUrgent_level
	 *            Integer
	 */
	public void setUrgent_level(Integer newUrgent_level) {
		this.urgent_level = newUrgent_level;
	}

	/**
	 * ����pk_carrier��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_carrier() {
		return pk_carrier;
	}

	/**
	 * ����pk_carrier��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_carrier
	 *            String
	 */
	public void setPk_carrier(String newPk_carrier) {
		this.pk_carrier = newPk_carrier;
	}

	/**
	 * ����arri_process��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getArri_process() {
		return arri_process;
	}

	/**
	 * ����arri_process��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newArri_process
	 *            String
	 */
	public void setArri_process(String newArri_process) {
		this.arri_process = newArri_process;
	}

	/**
	 * ����req_arri_time��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getReq_arri_time() {
		return req_arri_time;
	}

	/**
	 * ����req_arri_time��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newReq_arri_time
	 *            String
	 */
	public void setReq_arri_time(String newReq_arri_time) {
		this.req_arri_time = newReq_arri_time;
	}

	/**
	 * ����distance��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDouble
	 */
	public UFDouble getDistance() {
		return distance;
	}

	/**
	 * ����distance��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newDistance
	 *            UFDouble
	 */
	public void setDistance(UFDouble newDistance) {
		this.distance = newDistance;
	}

	/**
	 * ����memo��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����pk_invoice_type��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_invoice_type() {
		return pk_invoice_type;
	}

	/**
	 * ����pk_invoice_type��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_invoice_type
	 *            String
	 */
	public void setPk_invoice_type(String newPk_invoice_type) {
		this.pk_invoice_type = newPk_invoice_type;
	}

	public String getReq_arri_date() {
		return req_arri_date;
	}

	public void setReq_arri_date(String req_arri_date) {
		this.req_arri_date = req_arri_date;
	}

	public String getReq_deli_date() {
		return req_deli_date;
	}

	public void setReq_deli_date(String req_deli_date) {
		this.req_deli_date = req_deli_date;
	}

	/**
	 * ����weight_count��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDouble
	 */
	public UFDouble getWeight_count() {
		return weight_count;
	}

	/**
	 * ����weight_count��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newWeight_count
	 *            UFDouble
	 */
	public void setWeight_count(UFDouble newWeight_count) {
		this.weight_count = newWeight_count;
	}

	/**
	 * ����receipt_amount��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReceipt_amount() {
		return receipt_amount;
	}

	/**
	 * ����receipt_amount��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newReceipt_amount
	 *            UFDouble
	 */
	public void setReceipt_amount(UFDouble newReceipt_amount) {
		this.receipt_amount = newReceipt_amount;
	}

	/**
	 * ����note��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getNote() {
		return note;
	}

	/**
	 * ����note��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newNote
	 *            String
	 */
	public void setNote(String newNote) {
		this.note = newNote;
	}

	/**
	 * ����amount��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDouble
	 */
	public UFDouble getAmount() {
		return amount;
	}

	/**
	 * ����amount��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newAmount
	 *            UFDouble
	 */
	public void setAmount(UFDouble newAmount) {
		this.amount = newAmount;
	}

	/**
	 * ����cost_amount��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFDouble
	 */
	public UFDouble getCost_amount() {
		return cost_amount;
	}

	/**
	 * ����cost_amount��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newCost_amount
	 *            UFDouble
	 */
	public void setCost_amount(UFDouble newCost_amount) {
		this.cost_amount = newCost_amount;
	}

	/**
	 * ����pk_delivery��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_delivery() {
		return pk_delivery;
	}

	/**
	 * ����pk_delivery��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_delivery
	 *            String
	 */
	public void setPk_delivery(String newPk_delivery) {
		this.pk_delivery = newPk_delivery;
	}

	/**
	 * ����pk_invoice��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getPk_invoice() {
		return pk_invoice;
	}

	/**
	 * ����pk_invoice��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newPk_invoice
	 *            String
	 */
	public void setPk_invoice(String newPk_invoice) {
		this.pk_invoice = newPk_invoice;
	}

	public Integer getNum_count() {
		return num_count;
	}

	public void setNum_count(Integer num_count) {
		this.num_count = num_count;
	}

	/**
	 * ����deli_process��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getDeli_process() {
		return deli_process;
	}

	/**
	 * ����deli_process��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newDeli_process
	 *            String
	 */
	public void setDeli_process(String newDeli_process) {
		this.deli_process = newDeli_process;
	}

	public Integer getMileage() {
		return mileage;
	}

	public void setMileage(Integer mileage) {
		this.mileage = mileage;
	}

	/**
	 * ����if_backbill��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIf_backbill() {
		return if_backbill;
	}

	/**
	 * ����if_backbill��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newIf_backbill
	 *            UFBoolean
	 */
	public void setIf_backbill(UFBoolean newIf_backbill) {
		this.if_backbill = newIf_backbill;
	}

	/**
	 * ����insurance_no��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getInsurance_no() {
		return insurance_no;
	}

	/**
	 * ����insurance_no��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newInsurance_no
	 *            String
	 */
	public void setInsurance_no(String newInsurance_no) {
		this.insurance_no = newInsurance_no;
	}

	/**
	 * ����orderno��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getOrderno() {
		return orderno;
	}

	/**
	 * ����orderno��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newOrderno
	 *            String
	 */
	public void setOrderno(String newOrderno) {
		this.orderno = newOrderno;
	}

	/**
	 * ����customs_official_no��Getter����. ��������:2012-08-08 22:33:53
	 * 
	 * @return String
	 */
	public String getCustoms_official_no() {
		return customs_official_no;
	}

	/**
	 * ����customs_official_no��Setter����. ��������:2012-08-08 22:33:53
	 * 
	 * @param newCustoms_official_no
	 *            String
	 */
	public void setCustoms_official_no(String newCustoms_official_no) {
		this.customs_official_no = newCustoms_official_no;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-08-08 22:33:53
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-08-08 22:33:53
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_invoice";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-08-08 22:33:53
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_invoice";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-08-08 22:33:53
	 */
	public InvoiceVO() {
		super();
	}

	public Integer getUnconfirm_type() {
		return unconfirm_type;
	}

	public void setUnconfirm_type(Integer unconfirm_type) {
		this.unconfirm_type = unconfirm_type;
	}

	public String getUnconfirm_memo() {
		return unconfirm_memo;
	}

	public void setUnconfirm_memo(String unconfirm_memo) {
		this.unconfirm_memo = unconfirm_memo;
	}

	public String getConfirm_date() {
		return confirm_date;
	}

	public void setConfirm_date(String confirm_date) {
		this.confirm_date = confirm_date;
	}

	public String getConfirm_user() {
		return confirm_user;
	}

	public void setConfirm_user(String confirm_user) {
		this.confirm_user = confirm_user;
	}

	public String getUnconfirm_date() {
		return unconfirm_date;
	}

	public void setUnconfirm_date(String unconfirm_date) {
		this.unconfirm_date = unconfirm_date;
	}

	public String getUnconfirm_user() {
		return unconfirm_user;
	}

	public void setUnconfirm_user(String unconfirm_user) {
		this.unconfirm_user = unconfirm_user;
	}

	public String getPk_supplier() {
		return pk_supplier;
	}

	public void setPk_supplier(String pk_supplier) {
		this.pk_supplier = pk_supplier;
	}
	
}
