/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.pod;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 * 没有contentdata字段，该文件字段是特殊处理的
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PodAttachVO extends SuperVO {
	private String pk_invoice;
	private UFDateTime ts;
	private String pk_pod_attach;
	private Integer dr;
	private String file_name;
	private String suffix;
	private String memo;
	private String create_user;
	private UFDateTime create_time;
	private Long file_size;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String CONTENTDATA = "contentdata";
	public static final String FILE_SIZE = "file_size";
	public static final String PK_INVOICE = "pk_invoice";
	public static final String PK_POD_ATTACH = "pk_pod_attach";
	public static final String FILE_NAME = "file_name";
	public static final String SUFFIX = "suffix";
	public static final String MEMO = "memo";
	public static final String CREATE_USER = "create_user";
	public static final String CREATE_TIME = "create_time";

	public Long getFile_size() {
		return file_size;
	}

	public void setFile_size(Long file_size) {
		this.file_size = file_size;
	}

	public String getFile_name() {
		return file_name;
	}

	public void setFile_name(String file_name) {
		this.file_name = file_name;
	}

	public String getSuffix() {
		return suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	/**
	 * ����pk_invoice��Getter����. ��������:2013-04-16 19:16:38
	 * 
	 * @return String
	 */
	public String getPk_invoice() {
		return pk_invoice;
	}

	/**
	 * ����pk_invoice��Setter����. ��������:2013-04-16 19:16:38
	 * 
	 * @param newPk_invoice
	 *            String
	 */
	public void setPk_invoice(String newPk_invoice) {
		this.pk_invoice = newPk_invoice;
	}

	/**
	 * ����ts��Getter����. ��������:2013-04-16 19:16:38
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2013-04-16 19:16:38
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����pk_pod_attach��Getter����. ��������:2013-04-16 19:16:38
	 * 
	 * @return String
	 */
	public String getPk_pod_attach() {
		return pk_pod_attach;
	}

	/**
	 * ����pk_pod_attach��Setter����. ��������:2013-04-16 19:16:38
	 * 
	 * @param newPk_pod_attach
	 *            String
	 */
	public void setPk_pod_attach(String newPk_pod_attach) {
		this.pk_pod_attach = newPk_pod_attach;
	}

	/**
	 * ����dr��Getter����. ��������:2013-04-16 19:16:38
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2013-04-16 19:16:38
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * <p>
	 * ȡ�ø�VO����ֶ�.
	 * <p>
	 * ��������:2013-04-16 19:16:38
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_invoice";
	}

	/**
	 * <p>
	 * ȡ�ñ����.
	 * <p>
	 * ��������:2013-04-16 19:16:38
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_pod_attach";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2013-04-16 19:16:38
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_pod_attach";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2013-04-16 19:16:38
	 */
	public PodAttachVO() {
		super();
	}
}
