/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.vo.sys;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2012-07-07 22:05:47
 * 
 */
@SuppressWarnings("serial")
public class BillnoVO extends SuperVO {
	private String pk_billno;
	private UFDateTime ts;
	private String bill_type;
	private Integer dr;
	private Integer serial_no;
	private String pk_corp;

	public static final String PK_BILLNO = "pk_billno";
	public static final String BILL_TYPE = "bill_type";
	public static final String SERIAL_NO = "serial_no";
	public static final String PK_CORP = "pk_corp";

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	/**
	 * 属性pk_billno的Getter方法. 创建日期:2012-07-07 22:05:47
	 * 
	 * @return String
	 */
	public String getPk_billno() {
		return pk_billno;
	}

	/**
	 * 属性pk_billno的Setter方法. 创建日期:2012-07-07 22:05:47
	 * 
	 * @param newPk_billno
	 *            String
	 */
	public void setPk_billno(String newPk_billno) {
		this.pk_billno = newPk_billno;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2012-07-07 22:05:47
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2012-07-07 22:05:47
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	public String getBill_type() {
		return bill_type;
	}

	public void setBill_type(String bill_type) {
		this.bill_type = bill_type;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2012-07-07 22:05:47
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2012-07-07 22:05:47
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性serial_no的Getter方法. 创建日期:2012-07-07 22:05:47
	 * 
	 * @return Integer
	 */
	public Integer getSerial_no() {
		return serial_no;
	}

	/**
	 * 属性serial_no的Setter方法. 创建日期:2012-07-07 22:05:47
	 * 
	 * @param newSerial_no
	 *            Integer
	 */
	public void setSerial_no(Integer newSerial_no) {
		this.serial_no = newSerial_no;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-07-07 22:05:47
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-07-07 22:05:47
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_billno";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-07-07 22:05:47
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_billno";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-07-07 22:05:47
	 */
	public BillnoVO() {
		super();
	}
}
