/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.vo.sys;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;

/**
 * 
 */
@SuppressWarnings("serial")
public class CodenoVO extends SuperVO {
	private String pk_billno;
	private String fun_code;
	private UFDateTime ts;
	private Integer dr;
	private Integer serial_no;
	private String pk_corp;

	public static final String PK_BILLNO = "pk_billno";
	public static final String FUN_CODE = "fun_code";
	public static final String SERIAL_NO = "serial_no";
	public static final String PK_CORP = "pk_corp";

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	/**
	 * ����pk_billno��Getter����. ��������:2012-07-27 22:43:00
	 * 
	 * @return String
	 */
	public String getPk_billno() {
		return pk_billno;
	}

	/**
	 * ����pk_billno��Setter����. ��������:2012-07-27 22:43:00
	 * 
	 * @param newPk_billno
	 *            String
	 */
	public void setPk_billno(String newPk_billno) {
		this.pk_billno = newPk_billno;
	}

	/**
	 * ����fun_code��Getter����. ��������:2012-07-27 22:43:00
	 * 
	 * @return String
	 */
	public String getFun_code() {
		return fun_code;
	}

	/**
	 * ����fun_code��Setter����. ��������:2012-07-27 22:43:00
	 * 
	 * @param newFun_code
	 *            String
	 */
	public void setFun_code(String newFun_code) {
		this.fun_code = newFun_code;
	}

	/**
	 * ����ts��Getter����. ��������:2012-07-27 22:43:00
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-07-27 22:43:00
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����dr��Getter����. ��������:2012-07-27 22:43:00
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-07-27 22:43:00
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����serial_no��Getter����. ��������:2012-07-27 22:43:00
	 * 
	 * @return Integer
	 */
	public Integer getSerial_no() {
		return serial_no;
	}

	/**
	 * ����serial_no��Setter����. ��������:2012-07-27 22:43:00
	 * 
	 * @param newSerial_no
	 *            Integer
	 */
	public void setSerial_no(Integer newSerial_no) {
		this.serial_no = newSerial_no;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-07-27 22:43:00
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-07-27 22:43:00
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_billno";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-27 22:43:00
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_codeno";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-27 22:43:00
	 */
	public CodenoVO() {
		super();
	}
}
