/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.vo.sys;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;

/**
 */
@SuppressWarnings("serial")
public class DataDictBVO extends SuperVO {
	private String value;
	private String pk_data_dict;
	private String display_name;
	private String eng_display_name;
	private String pk_data_dict_b;
	private Integer display_order;
	private UFBoolean default_flag;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	//yaojiie 2015 12 08 增加数据字典明细中datatype_code，方便一次性查询时，使用。
	private String datatype_code;
	
	public String getDatatype_code() {
		return datatype_code;
	}

	public void setDatatype_code(String datatype_code) {
		this.datatype_code = datatype_code;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String VALUE = "value";
	public static final String PK_DATA_DICT = "pk_data_dict";
	public static final String DISPLAY_NAME = "display_name";
	public static final String ENG_DISPLAY_NAME = "eng_display_name";
	public static final String PK_DATA_DICT_B = "pk_data_dict_b";
	public static final String DISPLAY_ORDER = "display_order";

	public UFBoolean getDefault_flag() {
		return default_flag;
	}

	public void setDefault_flag(UFBoolean default_flag) {
		this.default_flag = default_flag;
	}

	public String getEng_display_name() {
		return eng_display_name;
	}

	public void setEng_display_name(String eng_display_name) {
		this.eng_display_name = eng_display_name;
	}

	public Integer getDisplay_order() {
		return display_order;
	}

	public void setDisplay_order(Integer display_order) {
		this.display_order = display_order;
	}

	/**
	 * ����value��Getter����. ��������:2012-07-15 17:41:46
	 * 
	 * @return String
	 */
	public String getValue() {
		return value;
	}

	/**
	 * ����value��Setter����. ��������:2012-07-15 17:41:46
	 * 
	 * @param newValue
	 *            String
	 */
	public void setValue(String newValue) {
		this.value = newValue;
	}

	/**
	 * ����pk_data_dict��Getter����. ��������:2012-07-15 17:41:46
	 * 
	 * @return String
	 */
	public String getPk_data_dict() {
		return pk_data_dict;
	}

	/**
	 * ����pk_data_dict��Setter����. ��������:2012-07-15 17:41:46
	 * 
	 * @param newPk_data_dict
	 *            String
	 */
	public void setPk_data_dict(String newPk_data_dict) {
		this.pk_data_dict = newPk_data_dict;
	}

	/**
	 * ����display_name��Getter����. ��������:2012-07-15 17:41:46
	 * 
	 * @return String
	 */
	public String getDisplay_name() {
		return display_name;
	}

	/**
	 * ����display_name��Setter����. ��������:2012-07-15 17:41:46
	 * 
	 * @param newDisplay_name
	 *            String
	 */
	public void setDisplay_name(String newDisplay_name) {
		this.display_name = newDisplay_name;
	}

	/**
	 * ����pk_data_dict_b��Getter����. ��������:2012-07-15 17:41:46
	 * 
	 * @return String
	 */
	public String getPk_data_dict_b() {
		return pk_data_dict_b;
	}

	/**
	 * ����pk_data_dict_b��Setter����. ��������:2012-07-15 17:41:46
	 * 
	 * @param newPk_data_dict_b
	 *            String
	 */
	public void setPk_data_dict_b(String newPk_data_dict_b) {
		this.pk_data_dict_b = newPk_data_dict_b;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-07-15 17:41:46
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_data_dict";
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-07-15 17:41:46
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_data_dict_b";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-15 17:41:46
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_data_dict_b";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-15 17:41:46
	 */
	public DataDictBVO() {
		super();
	}
}
