/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.vo.sys;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;

/**
 */
@SuppressWarnings("serial")
public class DataTempletVO extends SuperVO {
	
	private String pk_datatemplet;
	private String data_templetcaption;
	private Integer dr;
	private UFDateTime ts;
	private String pk_fun;
	private String nodecode;
	private String sql;
	private String sql_type;
	private String pk_corp;
	private String create_user;
	private UFDateTime create_time;
	private String modify_user;
	private UFDateTime modify_time;
	
	public static final String PK_DATATEMPLET = "pk_datatemplet";
	public static final String NW_DATATEMPLET = "nw_datatemplet";
	
	public String getPk_datatemplet() {
		return pk_datatemplet;
	}

	public void setPk_datatemplet(String pk_datatemplet) {
		this.pk_datatemplet = pk_datatemplet;
	}

	public String getData_templetcaption() {
		return data_templetcaption;
	}

	public void setData_templetcaption(String data_templetcaption) {
		this.data_templetcaption = data_templetcaption;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public String getPk_fun() {
		return pk_fun;
	}

	public void setPk_fun(String pk_fun) {
		this.pk_fun = pk_fun;
	}

	public String getNodecode() {
		return nodecode;
	}

	public void setNodecode(String nodecode) {
		this.nodecode = nodecode;
	}

	public String getSql_type() {
		return sql_type;
	}

	public void setSql_type(String sql_type) {
		this.sql_type = sql_type;
	}

	public String getSql() {
		return sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	@Override
	public String getParentPKFieldName() {
		return null;
	}

	@Override
	public String getPKFieldName() {
		return PK_DATATEMPLET;
	}

	@Override
	public String getTableName() {
		return NW_DATATEMPLET;
	}
	
}
