/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.vo.sys;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;

/**
 */
@SuppressWarnings("serial")
public class DeptVO extends SuperVO {
	private String pk_corp;
	private UFDateTime create_time;
	private String dept_name;
	private String dept_code;
	private String locked_flag;
	private String fatherdept;
	private UFDateTime ts;
	private Integer dr;
	private String pk_dept;
	private String create_user;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDateTime modify_time;
	private String modify_user;

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String PK_CORP = "pk_corp";
	public static final String CREATE_TIME = "create_time";
	public static final String DEPT_NAME = "dept_name";
	public static final String DEPT_CODE = "dept_code";
	public static final String LOCKED_FLAG = "locked_flag";
	public static final String FATHERDEPT = "fatherdept";
	public static final String PK_DEPT = "pk_dept";
	public static final String CREATE_USER = "create_user";

	/**
	 * ����pk_corp��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * ����pk_corp��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	/**
	 * ����dept_name��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return String
	 */
	public String getDept_name() {
		return dept_name;
	}

	/**
	 * ����dept_name��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newDept_name
	 *            String
	 */
	public void setDept_name(String newDept_name) {
		this.dept_name = newDept_name;
	}

	/**
	 * ����dept_code��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return String
	 */
	public String getDept_code() {
		return dept_code;
	}

	/**
	 * ����dept_code��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newDept_code
	 *            String
	 */
	public void setDept_code(String newDept_code) {
		this.dept_code = newDept_code;
	}

	/**
	 * ����locked_flag��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return String
	 */
	public String getLocked_flag() {
		return locked_flag;
	}

	/**
	 * ����locked_flag��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newLocked_flag
	 *            String
	 */
	public void setLocked_flag(String newLocked_flag) {
		this.locked_flag = newLocked_flag;
	}

	/**
	 * ����fatherdept��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return String
	 */
	public String getFatherdept() {
		return fatherdept;
	}

	/**
	 * ����fatherdept��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newFatherdept
	 *            String
	 */
	public void setFatherdept(String newFatherdept) {
		this.fatherdept = newFatherdept;
	}

	/**
	 * ����ts��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����dr��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����pk_dept��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return String
	 */
	public String getPk_dept() {
		return pk_dept;
	}

	/**
	 * ����pk_dept��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newPk_dept
	 *            String
	 */
	public void setPk_dept(String newPk_dept) {
		this.pk_dept = newPk_dept;
	}

	/**
	 * ����create_user��Getter����. ��������:2012-06-16 23:17:52
	 * 
	 * @return String
	 */
	public String getCreate_user() {
		return create_user;
	}

	/**
	 * ����create_user��Setter����. ��������:2012-06-16 23:17:52
	 * 
	 * @param newCreate_user
	 *            String
	 */
	public void setCreate_user(String newCreate_user) {
		this.create_user = newCreate_user;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-06-16 23:17:52
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-06-16 23:17:52
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_dept";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-06-16 23:17:52
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_dept";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-06-16 23:17:52
	 */
	public DeptVO() {
		super();
	}
}
