/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.vo.sys;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;

/**
 */
@SuppressWarnings("serial")
public class PowerFunVO extends SuperVO {
	private String pk_role;
	private String pk_fun;
	private String pk_power_fun;
	private UFDateTime ts;
	private Integer dr;

	public static final String PK_ROLE = "pk_role";
	public static final String PK_FUN = "pk_fun";
	public static final String PK_POWER_FUN = "pk_power_fun";

	/**
	 * ����pk_role��Getter����. ��������:2012-06-16 23:18:10
	 * 
	 * @return String
	 */
	public String getPk_role() {
		return pk_role;
	}

	/**
	 * ����pk_role��Setter����. ��������:2012-06-16 23:18:10
	 * 
	 * @param newPk_role
	 *            String
	 */
	public void setPk_role(String newPk_role) {
		this.pk_role = newPk_role;
	}

	/**
	 * ����pk_fun��Getter����. ��������:2012-06-16 23:18:10
	 * 
	 * @return String
	 */
	public String getPk_fun() {
		return pk_fun;
	}

	/**
	 * ����pk_fun��Setter����. ��������:2012-06-16 23:18:10
	 * 
	 * @param newPk_fun
	 *            String
	 */
	public void setPk_fun(String newPk_fun) {
		this.pk_fun = newPk_fun;
	}

	/**
	 * ����pk_power_fun��Getter����. ��������:2012-06-16 23:18:10
	 * 
	 * @return String
	 */
	public String getPk_power_fun() {
		return pk_power_fun;
	}

	/**
	 * ����pk_power_fun��Setter����. ��������:2012-06-16 23:18:10
	 * 
	 * @param newPk_power_fun
	 *            String
	 */
	public void setPk_power_fun(String newPk_power_fun) {
		this.pk_power_fun = newPk_power_fun;
	}

	/**
	 * ����ts��Getter����. ��������:2012-06-16 23:18:10
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-06-16 23:18:10
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����dr��Getter����. ��������:2012-06-16 23:18:10
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-06-16 23:18:10
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * <p>
	 * ȡ�ø�VO����ֶ�.
	 * <p>
	 * ��������:2012-06-16 23:18:10
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ����.
	 * <p>
	 * ��������:2012-06-16 23:18:10
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_power_fun";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-06-16 23:18:10
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_power_fun";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-06-16 23:18:10
	 */
	public PowerFunVO() {
		super();
	}
}
