/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.vo.sys;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;

/**
 */
@SuppressWarnings("serial")
public class TempletDistVO extends SuperVO {
	private String pk_role;
	private String pk_templet_dist;
	private String pk_fun;
	private Integer tempstyle;
	private UFDateTime ts;
	private String pk_user;
	private Integer dr;
	private String pk_templet;
	private String pk_corp;
	private String nodekey;
	private UFDateTime create_time;
	private String create_user;
	private UFDateTime modify_time;
	private String modify_user;

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public static final String PK_ROLE = "pk_role";
	public static final String PK_TEMPLET_DIST = "pk_templet_dist";
	public static final String PK_FUN = "pk_fun";
	public static final String TEMPSTYLE = "tempstyle";
	public static final String PK_USER = "pk_user";
	public static final String PK_TEMPLET = "pk_templet";
	public static final String PK_CORP = "pk_corp";

	public String getNodekey() {
		return nodekey;
	}

	public void setNodekey(String nodekey) {
		this.nodekey = nodekey;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	/**
	 * ����pk_role��Getter����. ��������:2012-07-08 11:35:15
	 * 
	 * @return String
	 */
	public String getPk_role() {
		return pk_role;
	}

	/**
	 * ����pk_role��Setter����. ��������:2012-07-08 11:35:15
	 * 
	 * @param newPk_role
	 *            String
	 */
	public void setPk_role(String newPk_role) {
		this.pk_role = newPk_role;
	}

	/**
	 * ����pk_templet_dist��Getter����. ��������:2012-07-08 11:35:15
	 * 
	 * @return String
	 */
	public String getPk_templet_dist() {
		return pk_templet_dist;
	}

	/**
	 * ����pk_templet_dist��Setter����. ��������:2012-07-08 11:35:15
	 * 
	 * @param newPk_templet_dist
	 *            String
	 */
	public void setPk_templet_dist(String newPk_templet_dist) {
		this.pk_templet_dist = newPk_templet_dist;
	}

	/**
	 * ����pk_fun��Getter����. ��������:2012-07-08 11:35:15
	 * 
	 * @return String
	 */
	public String getPk_fun() {
		return pk_fun;
	}

	/**
	 * ����pk_fun��Setter����. ��������:2012-07-08 11:35:15
	 * 
	 * @param newPk_fun
	 *            String
	 */
	public void setPk_fun(String newPk_fun) {
		this.pk_fun = newPk_fun;
	}

	/**
	 * ����tempstyle��Getter����. ��������:2012-07-08 11:35:15
	 * 
	 * @return Integer
	 */
	public Integer getTempstyle() {
		return tempstyle;
	}

	/**
	 * ����tempstyle��Setter����. ��������:2012-07-08 11:35:15
	 * 
	 * @param newTempstyle
	 *            Integer
	 */
	public void setTempstyle(Integer newTempstyle) {
		this.tempstyle = newTempstyle;
	}

	/**
	 * ����ts��Getter����. ��������:2012-07-08 11:35:15
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-07-08 11:35:15
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����pk_user��Getter����. ��������:2012-07-08 11:35:15
	 * 
	 * @return String
	 */
	public String getPk_user() {
		return pk_user;
	}

	/**
	 * ����pk_user��Setter����. ��������:2012-07-08 11:35:15
	 * 
	 * @param newPk_user
	 *            String
	 */
	public void setPk_user(String newPk_user) {
		this.pk_user = newPk_user;
	}

	/**
	 * ����dr��Getter����. ��������:2012-07-08 11:35:15
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-07-08 11:35:15
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����pk_templet��Getter����. ��������:2012-07-08 11:35:15
	 * 
	 * @return String
	 */
	public String getPk_templet() {
		return pk_templet;
	}

	/**
	 * ����pk_templet��Setter����. ��������:2012-07-08 11:35:15
	 * 
	 * @param newPk_templet
	 *            String
	 */
	public void setPk_templet(String newPk_templet) {
		this.pk_templet = newPk_templet;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-07-08 11:35:15
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-07-08 11:35:15
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_templet_dist";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-08 11:35:15
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_templet_dist";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-08 11:35:15
	 */
	public TempletDistVO() {
		super();
	}
}
