/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.vo.sys;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDate;
import org.nw.vo.pub.lang.UFDateTime;

/**
 */
@SuppressWarnings("serial")
public class UserVO extends SuperVO {
	private String pk_corp;
	private UFDateTime create_time;
	private String pk_role;
	private String user_name;
	private UFBoolean locked_flag;
	private String pk_user;
	private Integer dr;
	private Integer user_type;
	private UFDate disable_time;
	private String pk_dept;
	private String create_user;
	private UFDate able_time;
	private String user_code;
	private UFDateTime ts;
	private String user_password;
	private String user_note;
	private String email;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDateTime modify_time;
	private String modify_user;
	private String pk_psndoc;

	// 2015-05-15 增加客户和承运商，如果用户类型是客户，那么指定用户只能查询关联的客户的数据
	private String pk_customer;
	private String pk_carrier;
	
	// 2015-10-26  增加手机号  性别
	private String user_mobile;
	private String sex;
	private Integer platform_type;
	private String pk_address;
	private String language;
	
	
	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getPk_address() {
		return pk_address;
	}

	public void setPk_address(String pk_address) {
		this.pk_address = pk_address;
	}

	public Integer getPlatform_type() {
		return platform_type;
	}

	public void setPlatform_type(Integer platform_type) {
		this.platform_type = platform_type;
	}

	// yaojiie 2015 12 30 增加pk_driver字段
	private String pk_driver;

	public String getPk_driver() {
		return pk_driver;
	}

	public void setPk_driver(String pk_driver) {
		this.pk_driver = pk_driver;
	}
		
	public String getUser_mobile() {
		return user_mobile;
	}

	public void setUser_mobile(String user_mobile) {
		this.user_mobile = user_mobile;
	}
	
	public String getsex() {
		return sex;
	}

	public void setsex(String sex) {
		this.sex = sex;
	}
	
	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getPk_psndoc() {
		return pk_psndoc;
	}

	public void setPk_psndoc(String pk_psndoc) {
		this.pk_psndoc = pk_psndoc;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String PK_CORP = "pk_corp";
	public static final String CREATE_TIME = "create_time";
	public static final String PK_ROLE = "pk_role";
	public static final String USER_NAME = "user_name";
	public static final String LOCKED_FLAG = "locked_flag";
	public static final String PK_USER = "pk_user";
	public static final String USER_TYPE = "user_type";
	public static final String DISABLE_TIME = "disable_time";
	public static final String PK_DEPT = "pk_dept";
	public static final String CREATE_USER = "create_user";
	public static final String ABLE_TIME = "able_time";
	public static final String USER_CODE = "user_code";
	public static final String USER_PASSWORD = "user_password";
	public static final String USER_NOTE = "user_note";
	public static final String EMAIL = "email";
	public static final String PK_CUSTOMER = "pk_customer";
	public static final String PK_CARRIER = "pk_carrier";

	public String getPk_customer() {
		return pk_customer;
	}

	public void setPk_customer(String pk_customer) {
		this.pk_customer = pk_customer;
	}

	public String getPk_carrier() {
		return pk_carrier;
	}

	public void setPk_carrier(String pk_carrier) {
		this.pk_carrier = pk_carrier;
	}

	// 通过复制角色而来的，会使用该标识，复制角色的时候会同时复制角色的权限
	private String src_user;

	public String getSrc_user() {
		return src_user;
	}

	public void setSrc_user(String src_user) {
		this.src_user = src_user;
	}

	/**
	 * ����pk_corp��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * ����pk_corp��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	/**
	 * ����pk_role��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getPk_role() {
		return pk_role;
	}

	/**
	 * ����pk_role��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newPk_role
	 *            String
	 */
	public void setPk_role(String newPk_role) {
		this.pk_role = newPk_role;
	}

	/**
	 * ����user_name��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getUser_name() {
		return user_name;
	}

	/**
	 * ����user_name��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newUser_name
	 *            String
	 */
	public void setUser_name(String newUser_name) {
		this.user_name = newUser_name;
	}

	/**
	 * ����locked_flag��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getLocked_flag() {
		return locked_flag;
	}

	/**
	 * ����locked_flag��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newLocked_flag
	 *            UFBoolean
	 */
	public void setLocked_flag(UFBoolean newLocked_flag) {
		this.locked_flag = newLocked_flag;
	}

	/**
	 * ����pk_user��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getPk_user() {
		return pk_user;
	}

	/**
	 * ����pk_user��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newPk_user
	 *            String
	 */
	public void setPk_user(String newPk_user) {
		this.pk_user = newPk_user;
	}

	/**
	 * ����dr��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����user_type��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return Integer
	 */
	public Integer getUser_type() {
		return user_type;
	}

	/**
	 * ����user_type��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newUser_type
	 *            Integer
	 */
	public void setUser_type(Integer newUser_type) {
		this.user_type = newUser_type;
	}

	/**
	 * ����pk_dept��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getPk_dept() {
		return pk_dept;
	}

	/**
	 * ����pk_dept��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newPk_dept
	 *            String
	 */
	public void setPk_dept(String newPk_dept) {
		this.pk_dept = newPk_dept;
	}

	/**
	 * ����create_user��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getCreate_user() {
		return create_user;
	}

	/**
	 * ����create_user��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newCreate_user
	 *            String
	 */
	public void setCreate_user(String newCreate_user) {
		this.create_user = newCreate_user;
	}

	public UFDate getDisable_time() {
		return disable_time;
	}

	public void setDisable_time(UFDate disable_time) {
		this.disable_time = disable_time;
	}

	public UFDate getAble_time() {
		return able_time;
	}

	public void setAble_time(UFDate able_time) {
		this.able_time = able_time;
	}

	/**
	 * ����user_code��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getUser_code() {
		return user_code;
	}

	/**
	 * ����user_code��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newUser_code
	 *            String
	 */
	public void setUser_code(String newUser_code) {
		this.user_code = newUser_code;
	}

	/**
	 * ����ts��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����user_password��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getUser_password() {
		return user_password;
	}

	/**
	 * ����user_password��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newUser_password
	 *            String
	 */
	public void setUser_password(String newUser_password) {
		this.user_password = newUser_password;
	}

	/**
	 * ����user_note��Getter����. ��������:2012-06-16 23:18:39
	 * 
	 * @return String
	 */
	public String getUser_note() {
		return user_note;
	}

	/**
	 * ����user_note��Setter����. ��������:2012-06-16 23:18:39
	 * 
	 * @param newUser_note
	 *            String
	 */
	public void setUser_note(String newUser_note) {
		this.user_note = newUser_note;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-06-16 23:18:39
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-06-16 23:18:39
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_user";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-06-16 23:18:39
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_user";
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-06-16 23:18:39
	 */
	public UserVO() {
		super();
	}
}
