CREATE TABLE
    nw_billtemplet
    (
        bill_templetcaption VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        bill_templetname VARCHAR(40) COLLATE Chinese_PRC_CI_AS,
        dr SMALLINT DEFAULT 0,
        metadataclass VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        model_type CHAR(1) COLLATE Chinese_PRC_CI_AS,
        nodecode VARCHAR(30) COLLATE Chinese_PRC_CI_AS,
        OPTIONS VARCHAR(4000) COLLATE Chinese_PRC_CI_AS,
        pk_billtemplet CHAR(20) COLLATE Chinese_PRC_CI_AS NOT NULL,
        pk_billtypecode VARCHAR(12) COLLATE Chinese_PRC_CI_AS,
        pk_corp CHAR(4) COLLATE Chinese_PRC_CI_AS,
        resid VARCHAR(20) COLLATE Chinese_PRC_CI_AS,
        shareflag CHAR(1) COLLATE Chinese_PRC_CI_AS,
        ts CHAR(19) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([char](19),getdate(),(20))',
        validateformula VARCHAR(1000) COLLATE Chinese_PRC_CI_AS,
        create_user VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        create_time CHAR(19) COLLATE Chinese_PRC_CI_AS,
        modify_user VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        modify_time CHAR(19) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT pk_pub_billtemplet PRIMARY KEY (pk_billtemplet)
    );

    CREATE TABLE
    nw_billtemplet_b
    (
        cardflag SMALLINT DEFAULT 1,
        datatype INT DEFAULT 0,
        defaultshowname VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        defaultvalue VARCHAR(1000) COLLATE Chinese_PRC_CI_AS,
        dr SMALLINT DEFAULT 0,
        editflag SMALLINT DEFAULT 1,
        editformula VARCHAR(2000) COLLATE Chinese_PRC_CI_AS,
        foreground SMALLINT DEFAULT 0,
        idcolname VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        inputlength INT DEFAULT 20,
        itemkey VARCHAR(50) COLLATE Chinese_PRC_CI_AS NOT NULL,
        itemtype SMALLINT DEFAULT 0,
        leafflag CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N',
        listflag SMALLINT DEFAULT 1,
        listshowflag CHAR(1) COLLATE Chinese_PRC_CI_AS,
        loadformula VARCHAR(2000) COLLATE Chinese_PRC_CI_AS,
        lockflag SMALLINT DEFAULT 0,
        metadatapath VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        metadataproperty VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        metadatarelation VARCHAR(500) COLLATE Chinese_PRC_CI_AS,
        newlineflag CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N',
        nullflag SMALLINT DEFAULT 0,
        OPTIONS VARCHAR(4000) COLLATE Chinese_PRC_CI_AS,
        pk_billtemplet CHAR(20) COLLATE Chinese_PRC_CI_AS,
        pk_billtemplet_b CHAR(20) COLLATE Chinese_PRC_CI_AS NOT NULL,
        pk_corp CHAR(4) COLLATE Chinese_PRC_CI_AS DEFAULT '@@@@',
        pos INT DEFAULT 0,
        reftype VARCHAR(1000) COLLATE Chinese_PRC_CI_AS,
        resid VARCHAR(30) COLLATE Chinese_PRC_CI_AS,
        resid_tabname VARCHAR(30) COLLATE Chinese_PRC_CI_AS,
        reviseflag CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N',
        showflag SMALLINT DEFAULT 1,
        showorder INT DEFAULT 0,
        table_code VARCHAR(40) COLLATE Chinese_PRC_CI_AS,
        table_name VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        totalflag SMALLINT DEFAULT 0,
        ts CHAR(19) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([char](19),getdate(),(20))',
        userdefflag CHAR(1) COLLATE Chinese_PRC_CI_AS,
        userdefine1 VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        userdefine2 VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        userdefine3 VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        usereditflag SMALLINT DEFAULT 0,
        userflag SMALLINT DEFAULT 1,
        userreviseflag CHAR(1) COLLATE Chinese_PRC_CI_AS,
        usershowflag SMALLINT DEFAULT 0,
        validateformula VARCHAR(1000) COLLATE Chinese_PRC_CI_AS,
        width INT DEFAULT 1,
        CONSTRAINT pk_nw_billtemple2 PRIMARY KEY (pk_billtemplet_b),
        CONSTRAINT f_nw_billmodel_2 FOREIGN KEY (pk_billtemplet) REFERENCES nw_billtemplet
        (pk_billtemplet)
    );

    CREATE TABLE
    nw_billtemplet_t
    (
        basetab VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        dr SMALLINT DEFAULT 0,
        metadataclass VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        metadatapath VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        mixindex SMALLINT,
        pk_billtemplet CHAR(20) COLLATE Chinese_PRC_CI_AS,
        pk_billtemplet_t CHAR(20) COLLATE Chinese_PRC_CI_AS NOT NULL,
        pos SMALLINT,
        position SMALLINT,
        resid VARCHAR(30) COLLATE Chinese_PRC_CI_AS,
        tabcode VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        tabindex SMALLINT,
        tabname VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        ts CHAR(19) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([char](19),getdate(),(20))',
        vdef1 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        vdef2 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        vdef3 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT pk_pub_billtempl_t PRIMARY KEY (pk_billtemplet_t)
    );

    CREATE TABLE
    nw_query_templet
    (
        describe VARCHAR(300) COLLATE Chinese_PRC_CI_AS,
        dr SMALLINT DEFAULT 0,
        fixcondition VARCHAR(2000) COLLATE Chinese_PRC_CI_AS,
        id CHAR(20) COLLATE Chinese_PRC_CI_AS NOT NULL,
        metaclass VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        model_code VARCHAR(65) COLLATE Chinese_PRC_CI_AS,
        model_name VARCHAR(75) COLLATE Chinese_PRC_CI_AS,
        node_code VARCHAR(60) COLLATE Chinese_PRC_CI_AS NOT NULL,
        pk_corp CHAR(4) COLLATE Chinese_PRC_CI_AS NOT NULL,
        resid VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        ts CHAR(19) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([char](19),getdate(),(20))',
        create_user VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        create_time CHAR(19) COLLATE Chinese_PRC_CI_AS,
        modify_user VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        modify_time CHAR(19) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT pk_pub_query_templ PRIMARY KEY (id)
    );

    CREATE TABLE
    nw_query_condition
    (
        consult_code VARCHAR(1000) COLLATE Chinese_PRC_CI_AS DEFAULT '-99' NOT NULL,
        data_type INT DEFAULT 1 NOT NULL,
        disp_sequence INT DEFAULT 0 NOT NULL,
        disp_type SMALLINT DEFAULT 0 NOT NULL,
        disp_value VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        dr SMALLINT DEFAULT 0,
        field_code VARCHAR(100) COLLATE Chinese_PRC_CI_AS NOT NULL,
        field_name VARCHAR(100) COLLATE Chinese_PRC_CI_AS NOT NULL,
        guideline VARCHAR(1000) COLLATE Chinese_PRC_CI_AS,
        id CHAR(20) COLLATE Chinese_PRC_CI_AS NOT NULL,
        if_autocheck CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N' NOT NULL,
        if_datapower CHAR(1) COLLATE Chinese_PRC_CI_AS,
        if_default CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N' NOT NULL,
        if_desc CHAR(1) COLLATE Chinese_PRC_CI_AS,
        if_group CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N' NOT NULL,
        if_immobility CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N' NOT NULL,
        if_must CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N' NOT NULL,
        if_order CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N' NOT NULL,
        if_sum CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'N' NOT NULL,
        if_used CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'Y' NOT NULL,
        instrumentsql VARCHAR(4000) COLLATE Chinese_PRC_CI_AS,
        iscondition CHAR(1) COLLATE Chinese_PRC_CI_AS DEFAULT 'Y',
        max_length INT,
        opera_code VARCHAR(50) COLLATE Chinese_PRC_CI_AS NOT NULL,
        opera_name VARCHAR(100) COLLATE Chinese_PRC_CI_AS NOT NULL,
        order_sequence INT DEFAULT 0 NOT NULL,
        pk_corp CHAR(4) COLLATE Chinese_PRC_CI_AS NOT NULL,
        pk_templet CHAR(20) COLLATE Chinese_PRC_CI_AS NOT NULL,
        prerestrict VARCHAR(500) COLLATE Chinese_PRC_CI_AS,
        resid VARCHAR(30) COLLATE Chinese_PRC_CI_AS,
        return_type SMALLINT DEFAULT 0 NOT NULL,
        table_code VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        table_name VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        ts CHAR(19) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([char](19),getdate(),(20))',
        userdefflag CHAR(1) COLLATE Chinese_PRC_CI_AS,
        value VARCHAR(500) COLLATE Chinese_PRC_CI_AS,
        show_value VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT pk_pub_query_condi PRIMARY KEY (id)
    );
    
    CREATE TABLE
    nw_refinfo
    (
        code VARCHAR(100) COLLATE Chinese_PRC_CI_AS NOT NULL,
        dr SMALLINT DEFAULT 0,
        isneedpara CHAR(1) COLLATE Chinese_PRC_CI_AS,
        isspecialref CHAR(1) COLLATE Chinese_PRC_CI_AS,
        metadatatypename VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        module VARCHAR(100) COLLATE Chinese_PRC_CI_AS NOT NULL,
        name VARCHAR(500) COLLATE Chinese_PRC_CI_AS NOT NULL,
        para1 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        para2 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        para3 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        pk_refinfo CHAR(20) COLLATE Chinese_PRC_CI_AS NOT NULL,
        refclass VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        refsystem VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        reftype SMALLINT NOT NULL,
        reserv1 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        reserv2 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        reserv3 VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        resid VARCHAR(500) COLLATE Chinese_PRC_CI_AS NOT NULL,
        residpath VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        ts CHAR(19) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([char](19),getdate(),(20))',
        create_user VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        create_time CHAR(19) COLLATE Chinese_PRC_CI_AS,
        modify_user VARCHAR(50) COLLATE Chinese_PRC_CI_AS,
        modify_time CHAR(19) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT pk_bd_refinfo PRIMARY KEY (pk_refinfo)
    );