CREATE TABLE
    nw_billtemplet
    (
        bill_templetcaption VARCHAR(60) ,
        bill_templetname VARCHAR(40) ,
        dr SMALLINT DEFAULT 0,
        metadataclass VARCHAR(100) ,
        model_type CHAR(1) ,
        nodecode VARCHAR(30) ,
        OPTIONS VARCHAR(4000) ,
        pk_billtemplet CHAR(20)  NOT NULL,
        pk_billtypecode VARCHAR(12) ,
        pk_corp CHAR(4) ,
        resid VARCHAR(20) ,
        shareflag CHAR(1) ,
        ts CHAR(19)  ,
        validateformula VARCHAR(1000) ,
        create_user VARCHAR(50) ,
        create_time CHAR(19) ,
        modify_user VARCHAR(50) ,
        modify_time CHAR(19) ,
        CONSTRAINT pk_pub_billtemplet PRIMARY KEY (pk_billtemplet)
    );

    CREATE TABLE
    nw_billtemplet_b
    (
        cardflag SMALLINT DEFAULT 1,
        datatype INT DEFAULT 0,
        defaultshowname VARCHAR(100) ,
        defaultvalue VARCHAR(1000) ,
        dr SMALLINT DEFAULT 0,
        editflag SMALLINT DEFAULT 1,
        editformula VARCHAR(2000) ,
        foreground SMALLINT DEFAULT 0,
        idcolname VARCHAR(50) ,
        inputlength INT DEFAULT 20,
        itemkey VARCHAR(50)  NOT NULL,
        itemtype SMALLINT DEFAULT 0,
        leafflag CHAR(1)  DEFAULT 'N',
        listflag SMALLINT DEFAULT 1,
        listshowflag CHAR(1) ,
        loadformula VARCHAR(2000) ,
        lockflag SMALLINT DEFAULT 0,
        metadatapath VARCHAR(100) ,
        metadataproperty VARCHAR(100) ,
        metadatarelation VARCHAR(500) ,
        newlineflag CHAR(1)  DEFAULT 'N',
        nullflag SMALLINT DEFAULT 0,
        OPTIONS VARCHAR(4000) ,
        pk_billtemplet CHAR(20) ,
        pk_billtemplet_b CHAR(20)  NOT NULL,
        pk_corp CHAR(4)  DEFAULT '@@@@',
        pos INT DEFAULT 0,
        reftype VARCHAR(1000) ,
        resid VARCHAR(30) ,
        resid_tabname VARCHAR(30) ,
        reviseflag CHAR(1)  DEFAULT 'N',
        showflag SMALLINT DEFAULT 1,
        showorder INT DEFAULT 0,
        table_code VARCHAR(40) ,
        table_name VARCHAR(50) ,
        totalflag SMALLINT DEFAULT 0,
        ts CHAR(19)  ,
        userdefflag CHAR(1) ,
        userdefine1 VARCHAR(50) ,
        userdefine2 VARCHAR(50) ,
        userdefine3 VARCHAR(50) ,
        usereditflag SMALLINT DEFAULT 0,
        userflag SMALLINT DEFAULT 1,
        userreviseflag CHAR(1) ,
        usershowflag SMALLINT DEFAULT 0,
        validateformula VARCHAR(1000) ,
        width INT DEFAULT 1,
        CONSTRAINT pk_nw_billtemple2 PRIMARY KEY (pk_billtemplet_b),
        CONSTRAINT f_nw_billmodel_2 FOREIGN KEY (pk_billtemplet) REFERENCES nw_billtemplet
        (pk_billtemplet)
    );

    CREATE TABLE
    nw_billtemplet_t
    (
        basetab VARCHAR(50) ,
        dr SMALLINT DEFAULT 0,
        metadataclass VARCHAR(100) ,
        metadatapath VARCHAR(100) ,
        mixindex SMALLINT,
        pk_billtemplet CHAR(20) ,
        pk_billtemplet_t CHAR(20)  NOT NULL,
        pos SMALLINT,
        position SMALLINT,
        resid VARCHAR(30) ,
        tabcode VARCHAR(50) ,
        tabindex SMALLINT,
        tabname VARCHAR(50) ,
        ts CHAR(19)  ,
        vdef1 VARCHAR(100) ,
        vdef2 VARCHAR(100) ,
        vdef3 VARCHAR(100) ,
        CONSTRAINT pk_pub_billtempl_t PRIMARY KEY (pk_billtemplet_t)
    );

    CREATE TABLE
    nw_query_templet
    (
        `describe` VARCHAR(300) ,
        dr SMALLINT DEFAULT 0,
        fixcondition VARCHAR(2000) ,
        id CHAR(20)  NOT NULL,
        metaclass VARCHAR(200) ,
        model_code VARCHAR(65) ,
        model_name VARCHAR(75) ,
        node_code VARCHAR(60)  NOT NULL,
        pk_corp CHAR(4)  NOT NULL,
        resid VARCHAR(50) ,
        ts CHAR(19)  ,
        create_user VARCHAR(50) ,
        create_time CHAR(19) ,
        modify_user VARCHAR(50) ,
        modify_time CHAR(19) ,
        CONSTRAINT pk_pub_query_templ PRIMARY KEY (id)
    );

    CREATE TABLE
    nw_query_condition
    (
        consult_code VARCHAR(1000)  DEFAULT '-99' NOT NULL,
        data_type INT DEFAULT 1 NOT NULL,
        disp_sequence INT DEFAULT 0 NOT NULL,
        disp_type SMALLINT DEFAULT 0 NOT NULL,
        disp_value VARCHAR(50) ,
        dr SMALLINT DEFAULT 0,
        field_code VARCHAR(100)  NOT NULL,
        field_name VARCHAR(100)  NOT NULL,
        guideline VARCHAR(1000) ,
        id CHAR(20)  NOT NULL,
        if_autocheck CHAR(1)  DEFAULT 'N' NOT NULL,
        if_datapower CHAR(1) ,
        if_default CHAR(1)  DEFAULT 'N' NOT NULL,
        if_desc CHAR(1) ,
        if_group CHAR(1)  DEFAULT 'N' NOT NULL,
        if_immobility CHAR(1)  DEFAULT 'N' NOT NULL,
        if_must CHAR(1)  DEFAULT 'N' NOT NULL,
        if_order CHAR(1)  DEFAULT 'N' NOT NULL,
        if_sum CHAR(1)  DEFAULT 'N' NOT NULL,
        if_used CHAR(1)  DEFAULT 'Y' NOT NULL,
        instrumentsql VARCHAR(4000) ,
        iscondition CHAR(1)  DEFAULT 'Y',
        max_length INT,
        opera_code VARCHAR(50)  NOT NULL,
        opera_name VARCHAR(100)  NOT NULL,
        order_sequence INT DEFAULT 0 NOT NULL,
        pk_corp CHAR(4)  NOT NULL,
        pk_templet CHAR(20)  NOT NULL,
        prerestrict VARCHAR(500) ,
        resid VARCHAR(30) ,
        return_type SMALLINT DEFAULT 0 NOT NULL,
        table_code VARCHAR(100) ,
        table_name VARCHAR(50) ,
        ts CHAR(19)  ,
        userdefflag CHAR(1) ,
        value VARCHAR(500) ,
        show_value VARCHAR(100) ,
        CONSTRAINT pk_pub_query_condi PRIMARY KEY (id)
    );
    
    CREATE TABLE
    nw_refinfo
    (
        code VARCHAR(100)  NOT NULL,
        dr SMALLINT DEFAULT 0,
        isneedpara CHAR(1) ,
        isspecialref CHAR(1) ,
        metadatatypename VARCHAR(100) ,
        module VARCHAR(100)  NOT NULL,
        name VARCHAR(500)  NOT NULL,
        para1 VARCHAR(100) ,
        para2 VARCHAR(100) ,
        para3 VARCHAR(100) ,
        pk_refinfo CHAR(20)  NOT NULL,
        refclass VARCHAR(200) ,
        refsystem VARCHAR(100) ,
        reftype SMALLINT NOT NULL,
        reserv1 VARCHAR(100) ,
        reserv2 VARCHAR(100) ,
        reserv3 VARCHAR(100) ,
        resid VARCHAR(500)  NOT NULL,
        residpath VARCHAR(100) ,
        ts CHAR(19)  ,
        create_user VARCHAR(50) ,
        create_time CHAR(19) ,
        modify_user VARCHAR(50) ,
        modify_time CHAR(19) ,
        CONSTRAINT pk_bd_refinfo PRIMARY KEY (pk_refinfo)
    );