ALTER TABLE ACT_EVT_LOG ADD  DR INT;
ALTER TABLE ACT_EVT_LOG ADD  TS CHAR(19);
ALTER TABLE ACT_EVT_LOG ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_GE_BYTEARRAY ADD  DR INT;
ALTER TABLE ACT_GE_BYTEARRAY ADD  TS CHAR(19);
ALTER TABLE ACT_GE_BYTEARRAY ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_GE_PROPERTY ADD  DR INT;
ALTER TABLE ACT_GE_PROPERTY ADD  TS CHAR(19);
ALTER TABLE ACT_GE_PROPERTY ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_HI_ACTINST ADD  DR INT;
ALTER TABLE ACT_HI_ACTINST ADD  TS CHAR(19);
ALTER TABLE ACT_HI_ACTINST ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_HI_ATTACHMENT ADD  DR INT;
ALTER TABLE ACT_HI_ATTACHMENT ADD  TS CHAR(19);
ALTER TABLE ACT_HI_ATTACHMENT ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_HI_COMMENT ADD  DR INT;
ALTER TABLE ACT_HI_COMMENT ADD  TS CHAR(19);
ALTER TABLE ACT_HI_COMMENT ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_HI_DETAIL ADD  DR INT;
ALTER TABLE ACT_HI_DETAIL ADD  TS CHAR(19);
ALTER TABLE ACT_HI_DETAIL ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_HI_IDENTITYLINK ADD  DR INT;
ALTER TABLE ACT_HI_IDENTITYLINK ADD  TS CHAR(19);
ALTER TABLE ACT_HI_IDENTITYLINK ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_HI_PROCINST ADD  DR INT;
ALTER TABLE ACT_HI_PROCINST ADD  TS CHAR(19);
ALTER TABLE ACT_HI_PROCINST ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_HI_TASKINST ADD  DR INT;
ALTER TABLE ACT_HI_TASKINST ADD  TS CHAR(19);
ALTER TABLE ACT_HI_TASKINST ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_HI_VARINST ADD  DR INT;
ALTER TABLE ACT_HI_VARINST ADD  TS CHAR(19);
ALTER TABLE ACT_HI_VARINST ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RE_DEPLOYMENT ADD  DR INT;
ALTER TABLE ACT_RE_DEPLOYMENT ADD  TS CHAR(19);
ALTER TABLE ACT_RE_DEPLOYMENT ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RE_MODEL ADD  DR INT;
ALTER TABLE ACT_RE_MODEL ADD  TS CHAR(19);
ALTER TABLE ACT_RE_MODEL ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RE_PROCDEF ADD  DR INT;
ALTER TABLE ACT_RE_PROCDEF ADD  TS CHAR(19);
ALTER TABLE ACT_RE_PROCDEF ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RU_EVENT_SUBSCR ADD  DR INT;
ALTER TABLE ACT_RU_EVENT_SUBSCR ADD  TS CHAR(19);
ALTER TABLE ACT_RU_EVENT_SUBSCR ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RU_EXECUTION ADD  DR INT;
ALTER TABLE ACT_RU_EXECUTION ADD  TS CHAR(19);
ALTER TABLE ACT_RU_EXECUTION ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RU_IDENTITYLINK ADD  DR INT;
ALTER TABLE ACT_RU_IDENTITYLINK ADD  TS CHAR(19);
ALTER TABLE ACT_RU_IDENTITYLINK ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RU_JOB ADD  DR INT;
ALTER TABLE ACT_RU_JOB ADD  TS CHAR(19);
ALTER TABLE ACT_RU_JOB ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RU_TASK ADD  DR INT;
ALTER TABLE ACT_RU_TASK ADD  TS CHAR(19);
ALTER TABLE ACT_RU_TASK ADD  PK_CORP VARCHAR(50);

ALTER TABLE ACT_RU_VARIABLE ADD  DR INT;
ALTER TABLE ACT_RU_VARIABLE ADD  TS CHAR(19);
ALTER TABLE ACT_RU_VARIABLE ADD  PK_CORP VARCHAR(50);