--使用新的集成方式后，不需要创建视图了
--流程使用的view
CREATE VIEW ACT_ID_USER
AS 
	SELECT PK_USER AS ID_,1 AS REV_,USER_NAME AS FIRST_,USER_NOTE AS LAST_,EMAIL AS EMAIL_,USER_PASSWORD AS PWD_,'' AS PICTURE_ID_
	FROM NW_USER WHERE DR=0
GO

CREATE VIEW ACT_ID_GROUP
AS
	SELECT PK_ROLE AS ID_,1 AS REV_,ROLE_NAME AS NAME_,1 AS TYPE FROM NW_ROLE WHERE DR=0
GO

CREATE VIEW ACT_ID_MEMBERSHIP
AS 
	SELECT PK_USER AS USER_ID_,PK_ROLE AS GROUP_ID_ FROM NW_USER_ROLE WHERE DR=0
GO

CREATE VIEW ACT_ID_INFO
AS
	SELECT PK_USER AS ID_,1 AS REV_,PK_USER AS USER_ID_,1 AS TYPE_,'' AS KEY_,'' AS VALUE_,USER_PASSWORD AS PASSWORD_,'' AS PARENT_ID_ 
	FROM NW_USER WHERE DR=0
GO