/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.edi;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 */
@SuppressWarnings("serial")
public class EdiHisTransBilityBVO extends SuperVO {
	private Integer num;
	private String memo;
	private String pk_invoice;
	private String pk_trans_bility_b;
	private UFDateTime ts;
	private Integer dr;
	private String pk_car_type;
	private String carno;
	private String pk_driver;

	private UFDouble price;// 单价
	private UFDouble amount;// 金额
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	
	private org.nw.vo.pub.lang.UFDateTime sync_time;

	private org.nw.vo.pub.lang.UFBoolean syncexp_flag;

	private java.lang.String syncexp_memo;
	
	

	public org.nw.vo.pub.lang.UFDateTime getSync_time() {
		return sync_time;
	}

	public void setSync_time(org.nw.vo.pub.lang.UFDateTime sync_time) {
		this.sync_time = sync_time;
	}

	public org.nw.vo.pub.lang.UFBoolean getSyncexp_flag() {
		return syncexp_flag;
	}

	public void setSyncexp_flag(org.nw.vo.pub.lang.UFBoolean syncexp_flag) {
		this.syncexp_flag = syncexp_flag;
	}

	public java.lang.String getSyncexp_memo() {
		return syncexp_memo;
	}

	public void setSyncexp_memo(java.lang.String syncexp_memo) {
		this.syncexp_memo = syncexp_memo;
	}

	public String getCarno() {
		return carno;
	}

	public String getPk_driver() {
		return pk_driver;
	}


	public void setPk_driver(String pk_driver) {
		this.pk_driver = pk_driver;
	}




	public void setCarno(String carno) {
		this.carno = carno;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String NUM = "num";
	public static final String MEMO = "memo";
	public static final String PK_INVOICE = "pk_invoice";
	public static final String PK_TRANS_BILITY_B = "pk_trans_bility_b";
	public static final String PK_CAR_TYPE = "pk_car_type";
	public static final String PRICE = "price";
	public static final String AMOUNT = "amount";

	public UFDouble getPrice() {
		return price;
	}

	public void setPrice(UFDouble price) {
		this.price = price;
	}

	public UFDouble getAmount() {
		return amount;
	}

	public void setAmount(UFDouble amount) {
		this.amount = amount;
	}

	/**
	 * ����num��Getter����. ��������:2012-08-08 22:33:54
	 * 
	 * @return Integer
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * ����num��Setter����. ��������:2012-08-08 22:33:54
	 * 
	 * @param newNum
	 *            Integer
	 */
	public void setNum(Integer newNum) {
		this.num = newNum;
	}

	/**
	 * ����memo��Getter����. ��������:2012-08-08 22:33:54
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2012-08-08 22:33:54
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����pk_invoice��Getter����. ��������:2012-08-08 22:33:54
	 * 
	 * @return String
	 */
	public String getPk_invoice() {
		return pk_invoice;
	}

	/**
	 * ����pk_invoice��Setter����. ��������:2012-08-08 22:33:54
	 * 
	 * @param newPk_invoice
	 *            String
	 */
	public void setPk_invoice(String newPk_invoice) {
		this.pk_invoice = newPk_invoice;
	}

	/**
	 * ����pk_trans_bility_b��Getter����. ��������:2012-08-08 22:33:54
	 * 
	 * @return String
	 */
	public String getPk_trans_bility_b() {
		return pk_trans_bility_b;
	}

	/**
	 * ����pk_trans_bility_b��Setter����. ��������:2012-08-08 22:33:54
	 * 
	 * @param newPk_trans_bility_b
	 *            String
	 */
	public void setPk_trans_bility_b(String newPk_trans_bility_b) {
		this.pk_trans_bility_b = newPk_trans_bility_b;
	}

	/**
	 * ����ts��Getter����. ��������:2012-08-08 22:33:54
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-08-08 22:33:54
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����dr��Getter����. ��������:2012-08-08 22:33:54
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-08-08 22:33:54
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����pk_car_type��Getter����. ��������:2012-08-08 22:33:54
	 * 
	 * @return String
	 */
	public String getPk_car_type() {
		return pk_car_type;
	}

	/**
	 * ����pk_car_type��Setter����. ��������:2012-08-08 22:33:54
	 * 
	 * @param newPk_car_type
	 *            String
	 */
	public void setPk_car_type(String newPk_car_type) {
		this.pk_car_type = newPk_car_type;
	}

	/**
	 * <p>
	 * ȡ�ø�VO����ֶ�.
	 * <p>
	 * ��������:2012-08-08 22:33:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_invoice";
	}

	/**
	 * <p>
	 * ȡ�ñ����.
	 * <p>
	 * ��������:2012-08-08 22:33:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_trans_bility_b";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-08-08 22:33:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "edi_trans_bility_b";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-08-08 22:33:54
	 */
	public EdiHisTransBilityBVO() {
		super();
	}
}
