/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.base;

import org.nw.annotation.NotDBField;
import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 */
@SuppressWarnings("serial")
public class AddressVO extends SuperVO {
	private String pk_corp;
	private String phone;
	private String detail_addr;
	private String memo;
	private String mobile;
	private UFBoolean locked_flag;
	private String pk_address;
	private String pk_region;
	private Integer addr_type;
	private Integer dr;
	private String pk_country;
	private String addr_code;
	private String pk_city;
	private String fax;
	private UFDouble longitude;
	private String contact;
	private String pk_area;
	private UFDateTime ts;
	private String pk_province;
	private String email;
	private UFDouble latitude;
	private String addr_name;
	private String zipcode;
	private String contact_post;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	private UFDateTime create_time;
	private String create_user;
	private UFDateTime modify_time;
	private String modify_user;
	private String deli_process;
	private String arri_process;
	//yaojiie 2015 12 27 添加线路运力信息的字段，方便使用
	
	@NotDBField
	private String line_pk_driver;
	@NotDBField
	private String line_carno;
	@NotDBField
	private String line_pk_trans_type;
	@NotDBField
	private String line_pk_carrier;
	
	public String getLine_pk_driver() {
		return line_pk_driver;
	}

	public void setLine_pk_driver(String line_pk_driver) {
		this.line_pk_driver = line_pk_driver;
	}

	public String getLine_carno() {
		return line_carno;
	}

	public void setLine_carno(String line_carno) {
		this.line_carno = line_carno;
	}

	public String getLine_pk_trans_type() {
		return line_pk_trans_type;
	}

	public void setLine_pk_trans_type(String line_pk_trans_type) {
		this.line_pk_trans_type = line_pk_trans_type;
	}

	public String getLine_pk_carrier() {
		return line_pk_carrier;
	}

	public void setLine_pk_carrier(String line_pk_carrier) {
		this.line_pk_carrier = line_pk_carrier;
	}

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	// 扩展一个字段，方便使用
	@NotDBField
	private UFDouble s_timeline;

	public UFDouble getS_timeline() {
		return s_timeline;
	}

	public void setS_timeline(UFDouble s_timeline) {
		this.s_timeline = s_timeline;
	}
	
	// 扩展一个字段，方便使用
	private String pk_trans_line;

	public String getPk_trans_line() {
		return pk_trans_line;
	}

	public void setPk_trans_line(String pk_trans_line) {
		this.pk_trans_line = pk_trans_line;
	}

	public static final String PK_CORP = "pk_corp";
	public static final String PHONE = "phone";
	public static final String DETAIL_ADDR = "detail_addr";
	public static final String MEMO = "memo";
	public static final String MOBILE = "mobile";
	public static final String LOCKED_FLAG = "locked_flag";
	public static final String PK_ADDRESS = "pk_address";
	public static final String PK_REGION = "pk_region";
	public static final String ADDR_TYPE = "addr_type";
	public static final String PK_COUNTRY = "pk_country";
	public static final String ADDR_CODE = "addr_code";
	public static final String PK_CITY = "pk_city";
	public static final String FAX = "fax";
	public static final String LONGITUDE = "longitude";
	public static final String CONTACT = "contact";
	public static final String PK_AREA = "pk_area";
	public static final String PK_PROVINCE = "pk_province";
	public static final String EMAIL = "email";
	public static final String LATITUDE = "latitude";
	public static final String ADDR_NAME = "addr_name";
	public static final String ZIPCODE = "zipcode";
	public static final String CONTACT_POST = "contact_post";
	public static final String DELI_PROCESS = "deli_process";
	public static final String ARRI_PROCESS = "arri_process";

	public String getDeli_process() {
		return deli_process;
	}

	public void setDeli_process(String deli_process) {
		this.deli_process = deli_process;
	}

	public String getArri_process() {
		return arri_process;
	}

	public void setArri_process(String arri_process) {
		this.arri_process = arri_process;
	}

	public String getContact_post() {
		return contact_post;
	}

	public void setContact_post(String contact_post) {
		this.contact_post = contact_post;
	}

	/**
	 * ����pk_corp��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * ����pk_corp��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * ����phone��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * ����phone��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newPhone
	 *            String
	 */
	public void setPhone(String newPhone) {
		this.phone = newPhone;
	}

	/**
	 * ����detail_addr��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getDetail_addr() {
		return detail_addr;
	}

	/**
	 * ����detail_addr��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newDetail_addr
	 *            String
	 */
	public void setDetail_addr(String newDetail_addr) {
		this.detail_addr = newDetail_addr;
	}

	/**
	 * ����memo��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����mobile��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * ����mobile��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newMobile
	 *            String
	 */
	public void setMobile(String newMobile) {
		this.mobile = newMobile;
	}

	/**
	 * ����locked_flag��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getLocked_flag() {
		return locked_flag;
	}

	/**
	 * ����locked_flag��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newLocked_flag
	 *            UFBoolean
	 */
	public void setLocked_flag(UFBoolean newLocked_flag) {
		this.locked_flag = newLocked_flag;
	}

	/**
	 * ����pk_address��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getPk_address() {
		return pk_address;
	}

	/**
	 * ����pk_address��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newPk_address
	 *            String
	 */
	public void setPk_address(String newPk_address) {
		this.pk_address = newPk_address;
	}

	/**
	 * ����pk_region��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getPk_region() {
		return pk_region;
	}

	/**
	 * ����pk_region��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newPk_region
	 *            String
	 */
	public void setPk_region(String newPk_region) {
		this.pk_region = newPk_region;
	}

	/**
	 * ����addr_type��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return Integer
	 */
	public Integer getAddr_type() {
		return addr_type;
	}

	/**
	 * ����addr_type��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newAddr_type
	 *            Integer
	 */
	public void setAddr_type(Integer newAddr_type) {
		this.addr_type = newAddr_type;
	}

	/**
	 * ����dr��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����pk_country��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getPk_country() {
		return pk_country;
	}

	/**
	 * ����pk_country��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newPk_country
	 *            String
	 */
	public void setPk_country(String newPk_country) {
		this.pk_country = newPk_country;
	}

	/**
	 * ����pk_city��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getPk_city() {
		return pk_city;
	}

	/**
	 * ����pk_city��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newPk_city
	 *            String
	 */
	public void setPk_city(String newPk_city) {
		this.pk_city = newPk_city;
	}

	/**
	 * ����fax��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * ����fax��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newFax
	 *            String
	 */
	public void setFax(String newFax) {
		this.fax = newFax;
	}

	/**
	 * ����contact��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * ����contact��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newContact
	 *            String
	 */
	public void setContact(String newContact) {
		this.contact = newContact;
	}

	/**
	 * ����pk_area��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getPk_area() {
		return pk_area;
	}

	/**
	 * ����pk_area��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newPk_area
	 *            String
	 */
	public void setPk_area(String newPk_area) {
		this.pk_area = newPk_area;
	}

	/**
	 * ����ts��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����pk_province��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getPk_province() {
		return pk_province;
	}

	/**
	 * ����pk_province��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newPk_province
	 *            String
	 */
	public void setPk_province(String newPk_province) {
		this.pk_province = newPk_province;
	}

	/**
	 * ����email��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * ����email��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newEmail
	 *            String
	 */
	public void setEmail(String newEmail) {
		this.email = newEmail;
	}

	public UFDouble getLongitude() {
		return longitude;
	}

	public void setLongitude(UFDouble longitude) {
		this.longitude = longitude;
	}

	public UFDouble getLatitude() {
		return latitude;
	}

	public void setLatitude(UFDouble latitude) {
		this.latitude = latitude;
	}

	public String getAddr_code() {
		return addr_code;
	}

	public void setAddr_code(String addr_code) {
		this.addr_code = addr_code;
	}

	public String getAddr_name() {
		return addr_name;
	}

	public void setAddr_name(String addr_name) {
		this.addr_name = addr_name;
	}

	/**
	 * ����zipcode��Getter����. ��������:2012-07-25 11:38:26
	 * 
	 * @return String
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * ����zipcode��Setter����. ��������:2012-07-25 11:38:26
	 * 
	 * @param newZipcode
	 *            String
	 */
	public void setZipcode(String newZipcode) {
		this.zipcode = newZipcode;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-07-25 11:38:26
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-07-25 11:38:26
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_address";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-25 11:38:26
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_address";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-25 11:38:26
	 */
	public AddressVO() {
		super();
	}
}
