/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.base;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDate;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 */
@SuppressWarnings("serial")
public class CarPartVO extends SuperVO {
	private String memo;
	private String pk_car;
	private String unit;
	private Integer dr;
	private Integer istatus;
	private String pk_car_part;
	private String code;
	private UFDouble amount;
	private UFDate buy_date;
	private UFDateTime ts;
	private UFDouble price;
	private String name;
	private UFDouble quantity;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String MEMO = "memo";
	public static final String PK_CAR = "pk_car";
	public static final String UNIT = "unit";
	public static final String ISTATUS = "istatus";
	public static final String PK_CAR_PART = "pk_car_part";
	public static final String CODE = "code";
	public static final String AMOUNT = "amount";
	public static final String BUY_DATE = "buy_date";
	public static final String PRICE = "price";
	public static final String NAME = "name";
	public static final String QUANTITY = "quantity";

	public Integer getIstatus() {
		return istatus;
	}

	public void setIstatus(Integer istatus) {
		this.istatus = istatus;
	}

	/**
	 * ����memo��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����pk_car��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return String
	 */
	public String getPk_car() {
		return pk_car;
	}

	/**
	 * ����pk_car��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newPk_car
	 *            String
	 */
	public void setPk_car(String newPk_car) {
		this.pk_car = newPk_car;
	}

	/**
	 * ����unit��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return String
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * ����unit��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newUnit
	 *            String
	 */
	public void setUnit(String newUnit) {
		this.unit = newUnit;
	}

	/**
	 * ����dr��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����pk_car_part��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return String
	 */
	public String getPk_car_part() {
		return pk_car_part;
	}

	/**
	 * ����pk_car_part��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newPk_car_part
	 *            String
	 */
	public void setPk_car_part(String newPk_car_part) {
		this.pk_car_part = newPk_car_part;
	}

	/**
	 * ����code��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return String
	 */
	public String getCode() {
		return code;
	}

	/**
	 * ����code��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newCode
	 *            String
	 */
	public void setCode(String newCode) {
		this.code = newCode;
	}

	/**
	 * ����amount��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return UFDouble
	 */
	public UFDouble getAmount() {
		return amount;
	}

	/**
	 * ����amount��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newAmount
	 *            UFDouble
	 */
	public void setAmount(UFDouble newAmount) {
		this.amount = newAmount;
	}

	/**
	 * ����buy_date��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return UFDate
	 */
	public UFDate getBuy_date() {
		return buy_date;
	}

	/**
	 * ����buy_date��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newBuy_date
	 *            UFDate
	 */
	public void setBuy_date(UFDate newBuy_date) {
		this.buy_date = newBuy_date;
	}

	/**
	 * ����ts��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����price��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice() {
		return price;
	}

	/**
	 * ����price��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newPrice
	 *            UFDouble
	 */
	public void setPrice(UFDouble newPrice) {
		this.price = newPrice;
	}

	/**
	 * ����name��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/**
	 * ����name��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newName
	 *            String
	 */
	public void setName(String newName) {
		this.name = newName;
	}

	/**
	 * ����quantity��Getter����. ��������:2012-07-22 22:43:55
	 * 
	 * @return UFDouble
	 */
	public UFDouble getQuantity() {
		return quantity;
	}

	/**
	 * ����quantity��Setter����. ��������:2012-07-22 22:43:55
	 * 
	 * @param newQuantity
	 *            UFDouble
	 */
	public void setQuantity(UFDouble newQuantity) {
		this.quantity = newQuantity;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-07-22 22:43:55
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_car";
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-07-22 22:43:55
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_car_part";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-22 22:43:55
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_car_part";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-22 22:43:55
	 */
	public CarPartVO() {
		super();
	}
}
