/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.base;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDate;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 * <b> �ڴ˴���Ҫ��������Ĺ��� </b>
 * <p>
 * �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:2012-07-22 22:43:54
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class CarVO extends SuperVO {
	private String pk_corp;
	private UFDouble volume;
	private String actual_owner;
	private Integer car_status;
	private UFDouble width;
	private UFDouble l_fc_per_km;
	private UFDouble e_fc_per_km;
	private String manufacturer;
	private String carno;
	private UFDate filing_date;
	private Integer dr;
	private Integer corp_service_mileage;
	private Integer legal_service_date;
	private String brand;
	private UFDouble v_fc_per_km;
	private UFDate buy_date;
	private UFDouble height;
	private UFDateTime ts;
	private String chassis_no;
	private String photo;
	private String pk_carrier;
	private Integer priority;
	private String frame_no;
	private String memo;
	private UFDate output_date;
	private String pk_car;
	private UFBoolean locked_flag;
	private UFDouble length;
	private String trailer;
	private String tank;
	private String note;
	private String pk_car_type;
	private UFDouble gps_mileage;
	private String engine_no;
	private UFDouble load_weight;
	private Integer legal_service_mileage;
	private UFDouble mileage;
	private Integer car_prop;
	private UFDouble buy_amount;
	private String legal_owner;
	private UFDate lic_date;
	private String pk_driver;
	private String driver_mobile;
	private Integer corp_service_date;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	private String gps_id;
	private UFDateTime create_time;
	private String create_user;
	private UFDateTime modify_time;
	private String modify_user;
	
	private UFBoolean customs;
	private UFBoolean dangerous_veh;
	private String tonnage;
	private String White_card_number;
	private String driving_number;
	private UFDouble outside_length;
	private UFDouble outside_width;
	private UFDouble outside_height;
	private UFDateTime annual_date;
	private UFBoolean if_white;
	private Integer supervision_type;
	private Integer gps_lev;
	private UFDouble speed_limit;
	
	public UFDouble getSpeed_limit() {
		return speed_limit;
	}

	public void setSpeed_limit(UFDouble speed_limit) {
		this.speed_limit = speed_limit;
	}

	public String getDriving_number() {
		return driving_number;
	}

	public void setDriving_number(String driving_number) {
		this.driving_number = driving_number;
	}

	public UFDouble getOutside_length() {
		return outside_length;
	}

	public void setOutside_length(UFDouble outside_length) {
		this.outside_length = outside_length;
	}

	public UFDouble getOutside_width() {
		return outside_width;
	}

	public void setOutside_width(UFDouble outside_width) {
		this.outside_width = outside_width;
	}

	public UFDouble getOutside_height() {
		return outside_height;
	}

	public void setOutside_height(UFDouble outside_height) {
		this.outside_height = outside_height;
	}

	public UFDateTime getAnnual_date() {
		return annual_date;
	}

	public void setAnnual_date(UFDateTime annual_date) {
		this.annual_date = annual_date;
	}

	public UFBoolean getIf_white() {
		return if_white;
	}

	public void setIf_white(UFBoolean if_white) {
		this.if_white = if_white;
	}

	public Integer getSupervision_type() {
		return supervision_type;
	}

	public void setSupervision_type(Integer supervision_type) {
		this.supervision_type = supervision_type;
	}

	public Integer getGps_lev() {
		return gps_lev;
	}

	public void setGps_lev(Integer gps_lev) {
		this.gps_lev = gps_lev;
	}

	public UFBoolean getCustoms() {
		return customs;
	}

	public void setCustoms(UFBoolean customs) {
		this.customs = customs;
	}

	public UFBoolean getDangerous_veh() {
		return dangerous_veh;
	}

	public void setDangerous_veh(UFBoolean dangerous_veh) {
		this.dangerous_veh = dangerous_veh;
	}

	public String getTonnage() {
		return tonnage;
	}

	public void setTonnage(String tonnage) {
		this.tonnage = tonnage;
	}

	public String getWhite_card_number() {
		return White_card_number;
	}

	public void setWhite_card_number(String white_card_number) {
		White_card_number = white_card_number;
	}

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public String getGps_id() {
		return gps_id;
	}

	public void setGps_id(String gps_id) {
		this.gps_id = gps_id;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String PK_CORP = "pk_corp";
	public static final String VOLUME = "volume";
	public static final String ACTUAL_OWNER = "actual_owner";
	public static final String CAR_STATUS = "car_status";
	public static final String WIDTH = "width";
	public static final String L_FC_PER_KM = "l_fc_per_km";
	public static final String E_FC_PER_KM = "e_fc_per_km";
	public static final String MANUFACTURER = "manufacturer";
	public static final String CARNO = "carno";
	public static final String FILING_DATE = "filing_date";
	public static final String CORP_SERVICE_MILEAGE = "corp_service_mileage";
	public static final String LEGAL_SERVICE_DATE = "legal_service_date";
	public static final String BRAND = "brand";
	public static final String V_FC_PER_KM = "v_fc_per_km";
	public static final String BUY_DATE = "buy_date";
	public static final String HEIGHT = "height";
	public static final String CHASSIS_NO = "chassis_no";
	public static final String PHOTO = "photo";
	public static final String PK_CARRIER = "pk_carrier";
	public static final String PRIORITY = "priority";
	public static final String FRAME_NO = "frame_no";
	public static final String MEMO = "memo";
	public static final String OUTPUT_DATE = "output_date";
	public static final String PK_CAR = "pk_car";
	public static final String LOCKED_FLAG = "locked_flag";
	public static final String LENGTH = "length";
	public static final String TRAILER = "trailer";
	public static final String TANK = "tank";
	public static final String NOTE = "note";
	public static final String PK_CAR_TYPE = "pk_car_type";
	public static final String GPS_MILEAGE = "gps_mileage";
	public static final String ENGINE_NO = "engine_no";
	public static final String LOAD_WEIGHT = "load_weight";
	public static final String LEGAL_SERVICE_MILEAGE = "legal_service_mileage";
	public static final String MILEAGE = "mileage";
	public static final String CAR_PROP = "car_prop";
	public static final String BUY_AMOUNT = "buy_amount";
	public static final String LEGAL_OWNER = "legal_owner";
	public static final String LIC_DATE = "lic_date";
	public static final String PK_DRIVER = "pk_driver";
	public static final String DRIVER_MOBILE = "driver_mobile";
	public static final String CORP_SERVICE_DATE = "corp_service_date";
	public static final String GPS_ID = "gps_id";

	public String getDriver_mobile() {
		return driver_mobile;
	}

	public void setDriver_mobile(String driver_mobile) {
		this.driver_mobile = driver_mobile;
	}

	/**
	 * ����pk_corp��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * ����pk_corp��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * ����volume��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getVolume() {
		return volume;
	}

	/**
	 * ����volume��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newVolume
	 *            UFDouble
	 */
	public void setVolume(UFDouble newVolume) {
		this.volume = newVolume;
	}

	/**
	 * ����actual_owner��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getActual_owner() {
		return actual_owner;
	}

	/**
	 * ����actual_owner��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newActual_owner
	 *            String
	 */
	public void setActual_owner(String newActual_owner) {
		this.actual_owner = newActual_owner;
	}

	/**
	 * ����car_status��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return Integer
	 */
	public Integer getCar_status() {
		return car_status;
	}

	/**
	 * ����car_status��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newCar_status
	 *            Integer
	 */
	public void setCar_status(Integer newCar_status) {
		this.car_status = newCar_status;
	}

	/**
	 * ����width��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getWidth() {
		return width;
	}

	/**
	 * ����width��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newWidth
	 *            UFDouble
	 */
	public void setWidth(UFDouble newWidth) {
		this.width = newWidth;
	}

	/**
	 * ����l_fc_per_km��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getL_fc_per_km() {
		return l_fc_per_km;
	}

	/**
	 * ����l_fc_per_km��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newL_fc_per_km
	 *            UFDouble
	 */
	public void setL_fc_per_km(UFDouble newL_fc_per_km) {
		this.l_fc_per_km = newL_fc_per_km;
	}

	/**
	 * ����e_fc_per_km��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getE_fc_per_km() {
		return e_fc_per_km;
	}

	/**
	 * ����e_fc_per_km��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newE_fc_per_km
	 *            UFDouble
	 */
	public void setE_fc_per_km(UFDouble newE_fc_per_km) {
		this.e_fc_per_km = newE_fc_per_km;
	}

	/**
	 * ����manufacturer��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/**
	 * ����manufacturer��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newManufacturer
	 *            String
	 */
	public void setManufacturer(String newManufacturer) {
		this.manufacturer = newManufacturer;
	}

	/**
	 * ����carno��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getCarno() {
		return carno;
	}

	/**
	 * ����carno��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newCarno
	 *            String
	 */
	public void setCarno(String newCarno) {
		this.carno = newCarno;
	}

	/**
	 * ����filing_date��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDate
	 */
	public UFDate getFiling_date() {
		return filing_date;
	}

	/**
	 * ����filing_date��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newFiling_date
	 *            UFDate
	 */
	public void setFiling_date(UFDate newFiling_date) {
		this.filing_date = newFiling_date;
	}

	/**
	 * ����dr��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����corp_service_mileage��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return Integer
	 */
	public Integer getCorp_service_mileage() {
		return corp_service_mileage;
	}

	/**
	 * ����corp_service_mileage��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newCorp_service_mileage
	 *            Integer
	 */
	public void setCorp_service_mileage(Integer newCorp_service_mileage) {
		this.corp_service_mileage = newCorp_service_mileage;
	}

	public Integer getLegal_service_date() {
		return legal_service_date;
	}

	public void setLegal_service_date(Integer legal_service_date) {
		this.legal_service_date = legal_service_date;
	}

	public Integer getCorp_service_date() {
		return corp_service_date;
	}

	public void setCorp_service_date(Integer corp_service_date) {
		this.corp_service_date = corp_service_date;
	}

	/**
	 * ����brand��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * ����brand��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newBrand
	 *            String
	 */
	public void setBrand(String newBrand) {
		this.brand = newBrand;
	}

	/**
	 * ����v_fc_per_km��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getV_fc_per_km() {
		return v_fc_per_km;
	}

	/**
	 * ����v_fc_per_km��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newV_fc_per_km
	 *            UFDouble
	 */
	public void setV_fc_per_km(UFDouble newV_fc_per_km) {
		this.v_fc_per_km = newV_fc_per_km;
	}

	/**
	 * ����buy_date��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDate
	 */
	public UFDate getBuy_date() {
		return buy_date;
	}

	/**
	 * ����buy_date��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newBuy_date
	 *            UFDate
	 */
	public void setBuy_date(UFDate newBuy_date) {
		this.buy_date = newBuy_date;
	}

	/**
	 * ����height��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getHeight() {
		return height;
	}

	/**
	 * ����height��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newHeight
	 *            UFDouble
	 */
	public void setHeight(UFDouble newHeight) {
		this.height = newHeight;
	}

	/**
	 * ����ts��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����chassis_no��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getChassis_no() {
		return chassis_no;
	}

	/**
	 * ����chassis_no��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newChassis_no
	 *            String
	 */
	public void setChassis_no(String newChassis_no) {
		this.chassis_no = newChassis_no;
	}

	/**
	 * ����photo��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * ����photo��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newPhoto
	 *            String
	 */
	public void setPhoto(String newPhoto) {
		this.photo = newPhoto;
	}

	public String getPk_carrier() {
		return pk_carrier;
	}

	public void setPk_carrier(String pk_carrier) {
		this.pk_carrier = pk_carrier;
	}

	/**
	 * ����priority��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return Integer
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * ����priority��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newPriority
	 *            Integer
	 */
	public void setPriority(Integer newPriority) {
		this.priority = newPriority;
	}

	/**
	 * ����frame_no��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getFrame_no() {
		return frame_no;
	}

	/**
	 * ����frame_no��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newFrame_no
	 *            String
	 */
	public void setFrame_no(String newFrame_no) {
		this.frame_no = newFrame_no;
	}

	/**
	 * ����memo��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����output_date��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDate
	 */
	public UFDate getOutput_date() {
		return output_date;
	}

	/**
	 * ����output_date��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newOutput_date
	 *            UFDate
	 */
	public void setOutput_date(UFDate newOutput_date) {
		this.output_date = newOutput_date;
	}

	/**
	 * ����pk_car��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getPk_car() {
		return pk_car;
	}

	/**
	 * ����pk_car��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newPk_car
	 *            String
	 */
	public void setPk_car(String newPk_car) {
		this.pk_car = newPk_car;
	}

	/**
	 * ����locked_flag��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getLocked_flag() {
		return locked_flag;
	}

	/**
	 * ����locked_flag��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newLocked_flag
	 *            UFBoolean
	 */
	public void setLocked_flag(UFBoolean newLocked_flag) {
		this.locked_flag = newLocked_flag;
	}

	/**
	 * ����length��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getLength() {
		return length;
	}

	/**
	 * ����length��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newLength
	 *            UFDouble
	 */
	public void setLength(UFDouble newLength) {
		this.length = newLength;
	}

	/**
	 * ����trailer��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getTrailer() {
		return trailer;
	}

	/**
	 * ����trailer��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newTrailer
	 *            String
	 */
	public void setTrailer(String newTrailer) {
		this.trailer = newTrailer;
	}

	/**
	 * ����tank��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getTank() {
		return tank;
	}

	/**
	 * ����tank��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newTank
	 *            String
	 */
	public void setTank(String newTank) {
		this.tank = newTank;
	}

	/**
	 * ����note��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getNote() {
		return note;
	}

	/**
	 * ����note��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newNote
	 *            String
	 */
	public void setNote(String newNote) {
		this.note = newNote;
	}

	/**
	 * ����pk_car_type��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getPk_car_type() {
		return pk_car_type;
	}

	/**
	 * ����pk_car_type��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newPk_car_type
	 *            String
	 */
	public void setPk_car_type(String newPk_car_type) {
		this.pk_car_type = newPk_car_type;
	}

	/**
	 * ����gps_mileage��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getGps_mileage() {
		return gps_mileage;
	}

	/**
	 * ����gps_mileage��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newGps_mileage
	 *            UFDouble
	 */
	public void setGps_mileage(UFDouble newGps_mileage) {
		this.gps_mileage = newGps_mileage;
	}

	/**
	 * ����engine_no��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getEngine_no() {
		return engine_no;
	}

	/**
	 * ����engine_no��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newEngine_no
	 *            String
	 */
	public void setEngine_no(String newEngine_no) {
		this.engine_no = newEngine_no;
	}

	public UFDouble getLoad_weight() {
		return load_weight;
	}

	public void setLoad_weight(UFDouble load_weight) {
		this.load_weight = load_weight;
	}

	/**
	 * ����legal_service_mileage��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return Integer
	 */
	public Integer getLegal_service_mileage() {
		return legal_service_mileage;
	}

	/**
	 * ����legal_service_mileage��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newLegal_service_mileage
	 *            Integer
	 */
	public void setLegal_service_mileage(Integer newLegal_service_mileage) {
		this.legal_service_mileage = newLegal_service_mileage;
	}

	/**
	 * ����mileage��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMileage() {
		return mileage;
	}

	/**
	 * ����mileage��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newMileage
	 *            UFDouble
	 */
	public void setMileage(UFDouble newMileage) {
		this.mileage = newMileage;
	}

	/**
	 * ����car_prop��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return Integer
	 */
	public Integer getCar_prop() {
		return car_prop;
	}

	/**
	 * ����car_prop��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newCar_prop
	 *            Integer
	 */
	public void setCar_prop(Integer newCar_prop) {
		this.car_prop = newCar_prop;
	}

	/**
	 * ����buy_amount��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDouble
	 */
	public UFDouble getBuy_amount() {
		return buy_amount;
	}

	/**
	 * ����buy_amount��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newBuy_amount
	 *            UFDouble
	 */
	public void setBuy_amount(UFDouble newBuy_amount) {
		this.buy_amount = newBuy_amount;
	}

	/**
	 * ����legal_owner��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getLegal_owner() {
		return legal_owner;
	}

	/**
	 * ����legal_owner��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newLegal_owner
	 *            String
	 */
	public void setLegal_owner(String newLegal_owner) {
		this.legal_owner = newLegal_owner;
	}

	/**
	 * ����lic_date��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return UFDate
	 */
	public UFDate getLic_date() {
		return lic_date;
	}

	/**
	 * ����lic_date��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newLic_date
	 *            UFDate
	 */
	public void setLic_date(UFDate newLic_date) {
		this.lic_date = newLic_date;
	}

	/**
	 * ����pk_driver��Getter����. ��������:2012-07-22 22:43:54
	 * 
	 * @return String
	 */
	public String getPk_driver() {
		return pk_driver;
	}

	/**
	 * ����pk_driver��Setter����. ��������:2012-07-22 22:43:54
	 * 
	 * @param newPk_driver
	 *            String
	 */
	public void setPk_driver(String newPk_driver) {
		this.pk_driver = newPk_driver;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-07-22 22:43:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-07-22 22:43:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_car";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-22 22:43:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_car";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-22 22:43:54
	 */
	public CarVO() {
		super();
	}
}
