/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.base;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 * <b> �ڴ˴���Ҫ�������Ĺ��� </b>
 * <p>
 * �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:2012-07-17 23:18:32
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class CustBalaVO extends SuperVO {
	private UFBoolean locked_flag;
	private String pk_related_cust;
	private String pk_cust_bala;
	private String pk_customer;
	private UFBoolean is_default;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	private Integer dr;
	private UFDateTime ts;

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String LOCKED_FLAG = "locked_flag";
	public static final String PK_RELATED_CUST = "pk_related_cust";
	public static final String PK_CUST_BALA = "pk_cust_bala";
	public static final String PK_CUSTOMER = "pk_customer";
	public static final String IS_DEFAULT = "is_default";

	/**
	 * ����locked_flag��Getter����. ��������:2012-07-17 23:18:32
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getLocked_flag() {
		return locked_flag;
	}

	/**
	 * ����locked_flag��Setter����. ��������:2012-07-17 23:18:32
	 * 
	 * @param newLocked_flag
	 *            UFBoolean
	 */
	public void setLocked_flag(UFBoolean newLocked_flag) {
		this.locked_flag = newLocked_flag;
	}

	/**
	 * ����pk_related_cust��Getter����. ��������:2012-07-17 23:18:32
	 * 
	 * @return String
	 */
	public String getPk_related_cust() {
		return pk_related_cust;
	}

	/**
	 * ����pk_related_cust��Setter����. ��������:2012-07-17 23:18:32
	 * 
	 * @param newPk_related_cust
	 *            String
	 */
	public void setPk_related_cust(String newPk_related_cust) {
		this.pk_related_cust = newPk_related_cust;
	}

	/**
	 * ����pk_cust_bala��Getter����. ��������:2012-07-17 23:18:32
	 * 
	 * @return String
	 */
	public String getPk_cust_bala() {
		return pk_cust_bala;
	}

	/**
	 * ����pk_cust_bala��Setter����. ��������:2012-07-17 23:18:32
	 * 
	 * @param newPk_cust_bala
	 *            String
	 */
	public void setPk_cust_bala(String newPk_cust_bala) {
		this.pk_cust_bala = newPk_cust_bala;
	}

	/**
	 * ����pk_customer��Getter����. ��������:2012-07-17 23:18:32
	 * 
	 * @return String
	 */
	public String getPk_customer() {
		return pk_customer;
	}

	/**
	 * ����pk_customer��Setter����. ��������:2012-07-17 23:18:32
	 * 
	 * @param newPk_customer
	 *            String
	 */
	public void setPk_customer(String newPk_customer) {
		this.pk_customer = newPk_customer;
	}

	/**
	 * ����is_default��Getter����. ��������:2012-07-17 23:18:32
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIs_default() {
		return is_default;
	}

	/**
	 * ����is_default��Setter����. ��������:2012-07-17 23:18:32
	 * 
	 * @param newIs_default
	 *            UFBoolean
	 */
	public void setIs_default(UFBoolean newIs_default) {
		this.is_default = newIs_default;
	}

	/**
	 * <p>
	 * ȡ�ø�VO����ֶ�.
	 * <p>
	 * ��������:2012-07-17 23:18:32
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_customer";
	}

	/**
	 * <p>
	 * ȡ�ñ����.
	 * <p>
	 * ��������:2012-07-17 23:18:32
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_cust_bala";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-17 23:18:32
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_cust_bala";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-17 23:18:32
	 */
	public CustBalaVO() {
		super();
	}
}
