/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.base;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 * <b> �ڴ˴���Ҫ�������Ĺ��� </b>
 * <p>
 * �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:2012-07-23 20:39:27
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class GoodsPackcorpVO extends SuperVO {
	private String pk_corp;
	private UFDouble volume;
	private String memo;
	private UFDouble width;
	private String pk_goods_packcorp;
	private UFBoolean locked_flag;
	private UFDouble length;
	private Integer dr;
	private String code;
	private UFDouble height;
	private UFDateTime ts;
	private String name;
	private UFDouble weight;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	private UFDateTime create_time;
	private String create_user;
	private UFDateTime modify_time;
	private String modify_user;

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String PK_CORP = "pk_corp";
	public static final String VOLUME = "volume";
	public static final String MEMO = "memo";
	public static final String WIDTH = "width";
	public static final String PK_GOODS_PACKCORP = "pk_goods_packcorp";
	public static final String LOCKED_FLAG = "locked_flag";
	public static final String LENGTH = "length";
	public static final String CODE = "code";
	public static final String HEIGHT = "height";
	public static final String NAME = "name";
	public static final String WEIGHT = "weight";

	/**
	 * ����pk_corp��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * ����pk_corp��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * ����volume��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return UFDouble
	 */
	public UFDouble getVolume() {
		return volume;
	}

	/**
	 * ����volume��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newVolume
	 *            UFDouble
	 */
	public void setVolume(UFDouble newVolume) {
		this.volume = newVolume;
	}

	/**
	 * ����memo��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����width��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return UFDouble
	 */
	public UFDouble getWidth() {
		return width;
	}

	/**
	 * ����width��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newWidth
	 *            UFDouble
	 */
	public void setWidth(UFDouble newWidth) {
		this.width = newWidth;
	}

	/**
	 * ����pk_goods_packcorp��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return String
	 */
	public String getPk_goods_packcorp() {
		return pk_goods_packcorp;
	}

	/**
	 * ����pk_goods_packcorp��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newPk_goods_packcorp
	 *            String
	 */
	public void setPk_goods_packcorp(String newPk_goods_packcorp) {
		this.pk_goods_packcorp = newPk_goods_packcorp;
	}

	/**
	 * ����locked_flag��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getLocked_flag() {
		return locked_flag;
	}

	/**
	 * ����locked_flag��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newLocked_flag
	 *            UFBoolean
	 */
	public void setLocked_flag(UFBoolean newLocked_flag) {
		this.locked_flag = newLocked_flag;
	}

	/**
	 * ����length��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return UFDouble
	 */
	public UFDouble getLength() {
		return length;
	}

	/**
	 * ����length��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newLength
	 *            UFDouble
	 */
	public void setLength(UFDouble newLength) {
		this.length = newLength;
	}

	/**
	 * ����dr��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����code��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return String
	 */
	public String getCode() {
		return code;
	}

	/**
	 * ����code��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newCode
	 *            String
	 */
	public void setCode(String newCode) {
		this.code = newCode;
	}

	/**
	 * ����height��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return UFDouble
	 */
	public UFDouble getHeight() {
		return height;
	}

	/**
	 * ����height��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newHeight
	 *            UFDouble
	 */
	public void setHeight(UFDouble newHeight) {
		this.height = newHeight;
	}

	/**
	 * ����ts��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����name��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/**
	 * ����name��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newName
	 *            String
	 */
	public void setName(String newName) {
		this.name = newName;
	}

	/**
	 * ����weight��Getter����. ��������:2012-07-23 20:39:27
	 * 
	 * @return UFDouble
	 */
	public UFDouble getWeight() {
		return weight;
	}

	/**
	 * ����weight��Setter����. ��������:2012-07-23 20:39:27
	 * 
	 * @param newWeight
	 *            UFDouble
	 */
	public void setWeight(UFDouble newWeight) {
		this.weight = newWeight;
	}

	/**
	 * <p>
	 * ȡ�ø�VO����ֶ�.
	 * <p>
	 * ��������:2012-07-23 20:39:27
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_goods";
	}

	/**
	 * <p>
	 * ȡ�ñ����.
	 * <p>
	 * ��������:2012-07-23 20:39:27
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_goods_packcorp";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-23 20:39:27
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_goods_packcorp";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-23 20:39:27
	 */
	public GoodsPackcorpVO() {
		super();
	}
}
