/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.base;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDouble;

/**
 * <b> �ڴ˴���Ҫ��������Ĺ��� </b>
 * <p>
 * �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:2012-07-23 20:39:54
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class GoodsPackRelaVO extends SuperVO {
	private String pk_goods_packcorp;
	private String pk_goods;
	private UFBoolean if_default;
	private String pk_goods_pack_rela;
	private UFDouble length;
	private UFDouble width;
	private UFDouble height;
	private UFDouble volume;
	private UFDouble weight;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String PK_GOODS_PACKCORP = "pk_goods_packcorp";
	public static final String PK_GOODS = "pk_goods";
	public static final String IF_DEFAULT = "if_default";
	public static final String PK_GOODS_PACK_RELA = "pk_goods_pack_rela";
	public static final String LENGTH = "length";
	public static final String WIDTH = "width";
	public static final String HEIGHT = "height";
	public static final String VOLUME = "volume";
	public static final String WEIGHT = "weight";

	private String min_pack;
	private Integer pack_num;

	public static final String MIN_PACK = "min_pack";
	public static final String PACK_NUM = "pack_num";

	public String getMin_pack() {
		return min_pack;
	}

	public void setMin_pack(String min_pack) {
		this.min_pack = min_pack;
	}

	public Integer getPack_num() {
		return pack_num;
	}

	public void setPack_num(Integer pack_num) {
		this.pack_num = pack_num;
	}

	public UFDouble getLength() {
		return length;
	}

	public void setLength(UFDouble length) {
		this.length = length;
	}

	public UFDouble getWidth() {
		return width;
	}

	public void setWidth(UFDouble width) {
		this.width = width;
	}

	public UFDouble getHeight() {
		return height;
	}

	public void setHeight(UFDouble height) {
		this.height = height;
	}

	public UFDouble getVolume() {
		return volume;
	}

	public void setVolume(UFDouble volume) {
		this.volume = volume;
	}

	public UFDouble getWeight() {
		return weight;
	}

	public void setWeight(UFDouble weight) {
		this.weight = weight;
	}

	/**
	 * ����pk_goods_packcorp��Getter����. ��������:2012-07-23 20:39:54
	 * 
	 * @return String
	 */
	public String getPk_goods_packcorp() {
		return pk_goods_packcorp;
	}

	/**
	 * ����pk_goods_packcorp��Setter����. ��������:2012-07-23 20:39:54
	 * 
	 * @param newPk_goods_packcorp
	 *            String
	 */
	public void setPk_goods_packcorp(String newPk_goods_packcorp) {
		this.pk_goods_packcorp = newPk_goods_packcorp;
	}

	/**
	 * ����pk_goods��Getter����. ��������:2012-07-23 20:39:54
	 * 
	 * @return String
	 */
	public String getPk_goods() {
		return pk_goods;
	}

	/**
	 * ����pk_goods��Setter����. ��������:2012-07-23 20:39:54
	 * 
	 * @param newPk_goods
	 *            String
	 */
	public void setPk_goods(String newPk_goods) {
		this.pk_goods = newPk_goods;
	}

	/**
	 * ����if_default��Getter����. ��������:2012-07-23 20:39:54
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIf_default() {
		return if_default;
	}

	/**
	 * ����if_default��Setter����. ��������:2012-07-23 20:39:54
	 * 
	 * @param newIf_default
	 *            UFBoolean
	 */
	public void setIf_default(UFBoolean newIf_default) {
		this.if_default = newIf_default;
	}

	/**
	 * ����pk_goods_pack_rela��Getter����. ��������:2012-07-23 20:39:54
	 * 
	 * @return String
	 */
	public String getPk_goods_pack_rela() {
		return pk_goods_pack_rela;
	}

	/**
	 * ����pk_goods_pack_rela��Setter����. ��������:2012-07-23 20:39:54
	 * 
	 * @param newPk_goods_pack_rela
	 *            String
	 */
	public void setPk_goods_pack_rela(String newPk_goods_pack_rela) {
		this.pk_goods_pack_rela = newPk_goods_pack_rela;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-07-23 20:39:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_goods";
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-07-23 20:39:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_goods_pack_rela";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-07-23 20:39:54
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_goods_pack_rela";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-07-23 20:39:54
	 */
	public GoodsPackRelaVO() {
		super();
	}
}
