/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.base;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 */
@SuppressWarnings("serial")
public class OpProjectVO extends SuperVO {
	
	private String pk_op_project;
	private String code;
	private String name;
	private Integer dr;
	private UFDateTime ts;
	private String pk_customer;
	private String allocation1;
	private UFDouble proportion1;
	private String allocation2;
	private UFDouble proportion2;
	private String allocation3;
	private UFDouble proportion3;
	private String allocation4;
	private UFDouble proportion4;
	private String allocation5;
	private UFDouble proportion5;
	private String allocation6;
	private UFDouble proportion6;
	private String allocation7;
	private UFDouble proportion7;
	private String allocation8;
	private UFDouble proportion8;
	private String allocation9;
	private UFDouble proportion9;
	private String allocation10;
	private UFDouble proportion10;
	
	 
	private String memo;
	private String pk_corp;
	private UFBoolean locked_flag;

	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	private UFDateTime create_time;
	private String create_user;
	private UFDateTime modify_time;
	private String modify_user;
	
	public static final String PK_OP_PROJECT = "pk_op_project";
	public static final String TS_OP_PROJECT = "ts_op_project";
	
	
	
	public String getPk_op_project() {
		return pk_op_project;
	}
	public void setPk_op_project(String pk_op_project) {
		this.pk_op_project = pk_op_project;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public String getPk_customer() {
		return pk_customer;
	}
	public void setPk_customer(String pk_customer) {
		this.pk_customer = pk_customer;
	}
	public Integer getDr() {
		return dr;
	}
	public void setDr(Integer dr) {
		this.dr = dr;
	}
	public UFDateTime getTs() {
		return ts;
	}
	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}
	public String getAllocation1() {
		return allocation1;
	}
	public void setAllocation1(String allocation1) {
		this.allocation1 = allocation1;
	}
	public UFDouble getProportion1() {
		return proportion1;
	}
	public void setProportion1(UFDouble proportion1) {
		this.proportion1 = proportion1;
	}
	public String getAllocation2() {
		return allocation2;
	}
	public void setAllocation2(String allocation2) {
		this.allocation2 = allocation2;
	}
	public UFDouble getProportion2() {
		return proportion2;
	}
	public void setProportion2(UFDouble proportion2) {
		this.proportion2 = proportion2;
	}
	public String getAllocation3() {
		return allocation3;
	}
	public void setAllocation3(String allocation3) {
		this.allocation3 = allocation3;
	}
	public UFDouble getProportion3() {
		return proportion3;
	}
	public void setProportion3(UFDouble proportion3) {
		this.proportion3 = proportion3;
	}
	public String getAllocation4() {
		return allocation4;
	}
	public void setAllocation4(String allocation4) {
		this.allocation4 = allocation4;
	}
	public UFDouble getProportion4() {
		return proportion4;
	}
	public void setProportion4(UFDouble proportion4) {
		this.proportion4 = proportion4;
	}
	public String getAllocation5() {
		return allocation5;
	}
	public void setAllocation5(String allocation5) {
		this.allocation5 = allocation5;
	}
	public UFDouble getProportion5() {
		return proportion5;
	}
	public void setProportion5(UFDouble proportion5) {
		this.proportion5 = proportion5;
	}
	public String getAllocation6() {
		return allocation6;
	}
	public void setAllocation6(String allocation6) {
		this.allocation6 = allocation6;
	}
	public UFDouble getProportion6() {
		return proportion6;
	}
	public void setProportion6(UFDouble proportion6) {
		this.proportion6 = proportion6;
	}
	public String getAllocation7() {
		return allocation7;
	}
	public void setAllocation7(String allocation7) {
		this.allocation7 = allocation7;
	}
	public UFDouble getProportion7() {
		return proportion7;
	}
	public void setProportion7(UFDouble proportion7) {
		this.proportion7 = proportion7;
	}
	public String getAllocation8() {
		return allocation8;
	}
	public void setAllocation8(String allocation8) {
		this.allocation8 = allocation8;
	}
	public UFDouble getProportion8() {
		return proportion8;
	}
	public void setProportion8(UFDouble proportion8) {
		this.proportion8 = proportion8;
	}
	public String getAllocation9() {
		return allocation9;
	}
	public void setAllocation9(String allocation9) {
		this.allocation9 = allocation9;
	}
	public UFDouble getProportion9() {
		return proportion9;
	}
	public void setProportion9(UFDouble proportion9) {
		this.proportion9 = proportion9;
	}
	public String getAllocation10() {
		return allocation10;
	}
	public void setAllocation10(String allocation10) {
		this.allocation10 = allocation10;
	}
	public UFDouble getProportion10() {
		return proportion10;
	}
	public void setProportion10(UFDouble proportion10) {
		this.proportion10 = proportion10;
	}
	public String getMemo() {
		return memo;
	}
	public void setMemo(String memo) {
		this.memo = memo;
	}
	public String getPk_corp() {
		return pk_corp;
	}
	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}
	public UFBoolean getLocked_flag() {
		return locked_flag;
	}
	public void setLocked_flag(UFBoolean locked_flag) {
		this.locked_flag = locked_flag;
	}
	public String getDef10() {
		return def10;
	}
	public void setDef10(String def10) {
		this.def10 = def10;
	}
	public String getDef2() {
		return def2;
	}
	public void setDef2(String def2) {
		this.def2 = def2;
	}
	public String getDef1() {
		return def1;
	}
	public void setDef1(String def1) {
		this.def1 = def1;
	}
	public String getDef4() {
		return def4;
	}
	public void setDef4(String def4) {
		this.def4 = def4;
	}
	public String getDef3() {
		return def3;
	}
	public void setDef3(String def3) {
		this.def3 = def3;
	}
	public String getDef9() {
		return def9;
	}
	public void setDef9(String def9) {
		this.def9 = def9;
	}
	public String getDef5() {
		return def5;
	}
	public void setDef5(String def5) {
		this.def5 = def5;
	}
	public String getDef6() {
		return def6;
	}
	public void setDef6(String def6) {
		this.def6 = def6;
	}
	public String getDef7() {
		return def7;
	}
	public void setDef7(String def7) {
		this.def7 = def7;
	}
	public String getDef8() {
		return def8;
	}
	public void setDef8(String def8) {
		this.def8 = def8;
	}
	public UFDouble getDef11() {
		return def11;
	}
	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}
	public UFDouble getDef12() {
		return def12;
	}
	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}
	public UFDateTime getCreate_time() {
		return create_time;
	}
	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}
	public String getCreate_user() {
		return create_user;
	}
	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}
	public UFDateTime getModify_time() {
		return modify_time;
	}
	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}
	public String getModify_user() {
		return modify_user;
	}
	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}
	@Override
	public String getParentPKFieldName() {
		return null;
	}
	@Override
	public String getPKFieldName() {
		return PK_OP_PROJECT;
	}
	@Override
	public String getTableName() {
		return TS_OP_PROJECT;
	}

}
