alter table ts_ent_tracking add est_arri_time char(19);
alter table ts_entrust add est_arri_time char(19);

insert into ts_expense_type (pk_expense_type, dr, ts, code, name, type, pk_corp, memo, locked_flag, def1, def2, def3, def4, def5, def6, def7, def8, def9, def10, def11, def12) values ('b980f421ca4b4f689b261254bcdbe445', 0, '2014-12-21 19:25:15', 'ET40', '保险费', 2, '0001', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
insert into nw_parameter (pk_parameter, dr, ts, type, param_name, param_value, memo, pk_corp, create_user, create_time, modify_user, modify_time, def1, def2, def3, def4, def5, def6, def7, def8, def9, def10) values ('f9e2be2391ef4fc2a4b7c564b02ac93f', 0, '2014-12-23 21:35:19', 1, 'auto_gen_insurance', 'Y', '发货单费用明细是否自动生成对应类型的保险费', '0001', '0001', '2014-12-23 21:35:19', null, null, null, null, null, null, null, null, null, null, null, null);

--模板修改
insert into nw_billtemplet_b (cardflag, datatype, defaultshowname, defaultvalue, dr, editflag, editformula, foreground, idcolname, inputlength, itemkey, itemtype, leafflag, listflag, listshowflag, loadformula, lockflag, metadatapath, metadataproperty, metadatarelation, newlineflag, nullflag, OPTIONS, pk_billtemplet, pk_billtemplet_b, pk_corp, pos, reftype, resid, resid_tabname, reviseflag, showflag, showorder, table_code, table_name, totalflag, ts, userdefflag, userdefine1, userdefine2, userdefine3, usereditflag, userflag, userreviseflag, usershowflag, validateformula, width) values (1, 15, '预计到达时间', null, 0, 0, null, 0, null, 100, 'est_arri_time', 0, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '174611926RExa0001Sn4', '14402650906E0001Rfn0', '@@@@', 0, null, null, null, 'N', 1, 6, 'ts_ent_tracking', null, 0, '2014-12-23 14:40:27', 'N', null, null, null, 0, 1, 'N', 0, null, 1);
insert into nw_billtemplet_b (cardflag, datatype, defaultshowname, defaultvalue, dr, editflag, editformula, foreground, idcolname, inputlength, itemkey, itemtype, leafflag, listflag, listshowflag, loadformula, lockflag, metadatapath, metadataproperty, metadatarelation, newlineflag, nullflag, OPTIONS, pk_billtemplet, pk_billtemplet_b, pk_corp, pos, reftype, resid, resid_tabname, reviseflag, showflag, showorder, table_code, table_name, totalflag, ts, userdefflag, userdefine1, userdefine2, userdefine3, usereditflag, userflag, userreviseflag, usershowflag, validateformula, width) values (1, 15, '预计到达时间', null, 0, 0, null, 0, null, 100, 'est_arri_time', 0, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001A410000000001JEW', '22591544098E0001Qyq2', '@@@@', 0, null, null, null, 'N', 1, 16, 'ts_entrust', null, 0, '2014-12-23 22:59:16', 'N', null, null, null, 0, 1, 'N', 0, null, 1);
