/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.te;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;

/**
 */
@SuppressWarnings("serial")
public class EntInvBVO extends SuperVO {
	private String pk_invoice;
	private UFDateTime ts;
	private String pk_entrust;
	private String pk_ent_inv_b;
	private Integer dr;

	public static final String PK_INVOICE = "pk_invoice";
	public static final String PK_ENTRUST = "pk_entrust";
	public static final String PK_ENT_INV_B = "pk_ent_inv_b";

	/**
	 * ����pk_invoice��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_invoice() {
		return pk_invoice;
	}

	/**
	 * ����pk_invoice��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_invoice
	 *            String
	 */
	public void setPk_invoice(String newPk_invoice) {
		this.pk_invoice = newPk_invoice;
	}

	/**
	 * ����ts��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����pk_entrust��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_entrust() {
		return pk_entrust;
	}

	/**
	 * ����pk_entrust��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_entrust
	 *            String
	 */
	public void setPk_entrust(String newPk_entrust) {
		this.pk_entrust = newPk_entrust;
	}

	/**
	 * ����pk_ent_inv_b��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_ent_inv_b() {
		return pk_ent_inv_b;
	}

	/**
	 * ����pk_ent_inv_b��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_ent_inv_b
	 *            String
	 */
	public void setPk_ent_inv_b(String newPk_ent_inv_b) {
		this.pk_ent_inv_b = newPk_ent_inv_b;
	}

	/**
	 * ����dr��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-08-22 17:38:44
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_entrust";
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-08-22 17:38:44
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_ent_inv_b";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-08-22 17:38:44
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_ent_inv_b";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 *
	 * ��������:2012-08-22 17:38:44
	 */
	public EntInvBVO() {
		super();
	}
}
