/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.te;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 * <b> �ڴ˴���Ҫ��������Ĺ��� </b>
 * <p>
 * �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:2012-08-22 17:38:44
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class EntLinePackBVO extends SuperVO {
	
	private String pk_ent_line_pack_b;
	private String pk_entrust;
	private String pk_ent_line_b;
	
	private UFDouble volume;
	private UFDouble hight_temp;
	private String memo;
	private UFDouble width;
	private String pk_ent_pack_b;
	private UFDouble length;
	private String pk_goods;
	private Integer dr;
	private String goods_code;
	private UFDouble unit_weight;
	private String reference_no;
	private String goods_name;
	private Integer num;
	private Integer serialno;
	private UFDouble height;
	private String pack;
	private UFDateTime ts;
	private UFDouble unit_volume;
	private UFDouble low_temp;
	private UFDouble weight;
	private String trans_note;
	private UFDouble pack_num_count;

	private Integer plan_num;
	private UFDouble plan_pack_num_count;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def10;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;

	public static final String PK_ENT_PACK_B = "pk_ent_pack_b";
	public static final String PK_ENTRUST = "pk_entrust";
	public static final String PK_ENT_LINE_PACK_B = "pk_ent_line_pack_b";

	
	
	

	public String getPk_ent_line_pack_b() {
		return pk_ent_line_pack_b;
	}

	public void setPk_ent_line_pack_b(String pk_ent_line_pack_b) {
		this.pk_ent_line_pack_b = pk_ent_line_pack_b;
	}

	public String getPk_entrust() {
		return pk_entrust;
	}

	public void setPk_entrust(String pk_entrust) {
		this.pk_entrust = pk_entrust;
	}

	public String getPk_ent_line_b() {
		return pk_ent_line_b;
	}

	public void setPk_ent_line_b(String pk_ent_line_b) {
		this.pk_ent_line_b = pk_ent_line_b;
	}

	public UFDouble getVolume() {
		return volume;
	}

	public void setVolume(UFDouble volume) {
		this.volume = volume;
	}

	public UFDouble getHight_temp() {
		return hight_temp;
	}

	public void setHight_temp(UFDouble hight_temp) {
		this.hight_temp = hight_temp;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public UFDouble getWidth() {
		return width;
	}

	public void setWidth(UFDouble width) {
		this.width = width;
	}

	public String getPk_ent_pack_b() {
		return pk_ent_pack_b;
	}

	public void setPk_ent_pack_b(String pk_ent_pack_b) {
		this.pk_ent_pack_b = pk_ent_pack_b;
	}

	public UFDouble getLength() {
		return length;
	}

	public void setLength(UFDouble length) {
		this.length = length;
	}

	public String getPk_goods() {
		return pk_goods;
	}

	public void setPk_goods(String pk_goods) {
		this.pk_goods = pk_goods;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public String getGoods_code() {
		return goods_code;
	}

	public void setGoods_code(String goods_code) {
		this.goods_code = goods_code;
	}

	public UFDouble getUnit_weight() {
		return unit_weight;
	}

	public void setUnit_weight(UFDouble unit_weight) {
		this.unit_weight = unit_weight;
	}

	public String getReference_no() {
		return reference_no;
	}

	public void setReference_no(String reference_no) {
		this.reference_no = reference_no;
	}

	public String getGoods_name() {
		return goods_name;
	}

	public void setGoods_name(String goods_name) {
		this.goods_name = goods_name;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Integer getSerialno() {
		return serialno;
	}

	public void setSerialno(Integer serialno) {
		this.serialno = serialno;
	}

	public UFDouble getHeight() {
		return height;
	}

	public void setHeight(UFDouble height) {
		this.height = height;
	}

	public String getPack() {
		return pack;
	}

	public void setPack(String pack) {
		this.pack = pack;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public UFDouble getUnit_volume() {
		return unit_volume;
	}

	public void setUnit_volume(UFDouble unit_volume) {
		this.unit_volume = unit_volume;
	}

	public UFDouble getLow_temp() {
		return low_temp;
	}

	public void setLow_temp(UFDouble low_temp) {
		this.low_temp = low_temp;
	}

	public UFDouble getWeight() {
		return weight;
	}

	public void setWeight(UFDouble weight) {
		this.weight = weight;
	}

	public String getTrans_note() {
		return trans_note;
	}

	public void setTrans_note(String trans_note) {
		this.trans_note = trans_note;
	}

	public UFDouble getPack_num_count() {
		return pack_num_count;
	}

	public void setPack_num_count(UFDouble pack_num_count) {
		this.pack_num_count = pack_num_count;
	}

	public Integer getPlan_num() {
		return plan_num;
	}

	public void setPlan_num(Integer plan_num) {
		this.plan_num = plan_num;
	}

	public UFDouble getPlan_pack_num_count() {
		return plan_pack_num_count;
	}

	public void setPlan_pack_num_count(UFDouble plan_pack_num_count) {
		this.plan_pack_num_count = plan_pack_num_count;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public static String getPkEntPackB() {
		return PK_ENT_PACK_B;
	}

	public static String getPkEntrust() {
		return PK_ENTRUST;
	}

	public static String getPkEntLinePackB() {
		return PK_ENT_LINE_PACK_B;
	}

	public java.lang.String getParentPKFieldName() {
		return "pk_entrust";
	}
	
	public java.lang.String getPKFieldName() {
		return "pk_ent_line_pack_b";
	}
	
	public java.lang.String getTableName() {
		return "ts_ent_line_pack_b";
	}
	
	public EntLinePackBVO() {
		super();
	}
}
