/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.te;

import java.util.List;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 */
@SuppressWarnings("serial")
public class EntLineBVO extends SuperVO {
	private String detail_addr;
	private String phone;
	private String req_leav_date;
	private String req_arri_date;
	private String act_leav_date;
	private String act_arri_date;
	private String req_leav_time;
	private String req_arri_time;
	private String memo;
	private String mobile;
	private String pk_address;
	private String pk_entrust;
	private String pk_ent_line_b;
	private Integer dr;
	private String pk_city;
	private Integer serialno;
	private String contact;
	private String pk_area;
	private UFDateTime ts;
	private String pk_province;
	private String email;
	private String addr_flag; // S表示始发地，E表示目的地,如果多个运段，使用分号分开
	private String pk_segment;
	private UFBoolean arrival_flag;// 是否到货标识
	private UFBoolean segment_node;// 是否是运段的节点，区分用户自己增加的节点
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	//yaojiie 2015 12 07 增加APP使用的字段
	//yaojiie 2015 12 07 修改字段名
	private UFDouble curr_longitude;
	private UFDouble curr_latitude ;
	private UFDouble mileage ;
	private String app_detail_addr;

	private String addr_name;// 扩展一个地址名称字段，方便调试

	// 扩展字段，批量节点到货时，需要根据这个号码进行排序。
	private String segment_vbillno;// 运段号
	//yaojiie 2015 12 29 增加操作类型字段
	private Integer operate_type;// 操作类型
	
	//2016-01-06 songf 增加货品明细子表
	List<EntLinePackBVO> EntLinePackBVOs;
	
	//2016-01-06 songf  增加操作名称
	private String operate_name;
	
	public Integer getOperate_type() {
		return operate_type;
	}

	public void setOperate_type(Integer operate_type) {
		this.operate_type = operate_type;
	}

	public String getSegment_vbillno() {
		return segment_vbillno;
	}

	public void setSegment_vbillno(String segment_vbillno) {
		this.segment_vbillno = segment_vbillno;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String DETAIL_ADDR = "detail_addr";
	public static final String PHONE = "phone";
	public static final String REQ_LEAV_TIME = "req_leav_time";
	public static final String REQ_ARRI_TIME = "req_arri_time";
	public static final String REQ_LEAV_DATE = "req_leav_date";
	public static final String REQ_ARRI_DATE = "req_arri_date";
	public static final String ACT_LEAV_DATE = "act_leav_date";
	public static final String ACT_ARRI_DATE = "act_arri_date";
	public static final String MEMO = "memo";
	public static final String MOBILE = "mobile";
	public static final String PK_ADDRESS = "pk_address";
	public static final String PK_ENTRUST = "pk_entrust";
	public static final String PK_ENT_LINE_B = "pk_ent_line_b";
	public static final String PK_CITY = "pk_city";
	public static final String SERIALNO = "serialno";
	public static final String CONTACT = "contact";
	public static final String PK_AREA = "pk_area";
	public static final String PK_PROVINCE = "pk_province";
	public static final String EMAIL = "email";
	public static final String ADDR_FLAG = "addr_flag";
	public static final String END_ADDR_FLAG = "end_addr_flag";
	public static final String PK_SEGMENT = "pk_segment";
	public static final String ARRIVAL_FLAG = "arrival_flag";

	public String getAddr_name() {
		return addr_name;
	}

	public void setAddr_name(String addr_name) {
		this.addr_name = addr_name;
	}

	public UFBoolean getSegment_node() {
		return segment_node;
	}

	public void setSegment_node(UFBoolean segment_node) {
		this.segment_node = segment_node;
	}

	public UFBoolean getArrival_flag() {
		return arrival_flag;
	}

	public void setArrival_flag(UFBoolean arrival_flag) {
		this.arrival_flag = arrival_flag;
	}

	public String getAct_leav_date() {
		return act_leav_date;
	}

	public void setAct_leav_date(String act_leav_date) {
		this.act_leav_date = act_leav_date;
	}

	public String getAct_arri_date() {
		return act_arri_date;
	}

	public void setAct_arri_date(String act_arri_date) {
		this.act_arri_date = act_arri_date;
	}

	public String getAddr_flag() {
		return addr_flag;
	}

	public void setAddr_flag(String addr_flag) {
		this.addr_flag = addr_flag;
	}

	public String getPk_segment() {
		return pk_segment;
	}

	public void setPk_segment(String pk_segment) {
		this.pk_segment = pk_segment;
	}

	public String getReq_leav_date() {
		return req_leav_date;
	}

	public void setReq_leav_date(String req_leav_date) {
		this.req_leav_date = req_leav_date;
	}

	public String getReq_arri_date() {
		return req_arri_date;
	}

	public void setReq_arri_date(String req_arri_date) {
		this.req_arri_date = req_arri_date;
	}

	/**
	 * ����detail_addr��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getDetail_addr() {
		return detail_addr;
	}

	/**
	 * ����detail_addr��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newDetail_addr
	 *            String
	 */
	public void setDetail_addr(String newDetail_addr) {
		this.detail_addr = newDetail_addr;
	}

	/**
	 * ����phone��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * ����phone��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPhone
	 *            String
	 */
	public void setPhone(String newPhone) {
		this.phone = newPhone;
	}

	public String getReq_leav_time() {
		return req_leav_time;
	}

	public void setReq_leav_time(String req_leav_time) {
		this.req_leav_time = req_leav_time;
	}

	public String getReq_arri_time() {
		return req_arri_time;
	}

	public void setReq_arri_time(String req_arri_time) {
		this.req_arri_time = req_arri_time;
	}

	/**
	 * ����memo��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����mobile��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * ����mobile��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newMobile
	 *            String
	 */
	public void setMobile(String newMobile) {
		this.mobile = newMobile;
	}

	/**
	 * ����pk_address��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_address() {
		return pk_address;
	}

	/**
	 * ����pk_address��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_address
	 *            String
	 */
	public void setPk_address(String newPk_address) {
		this.pk_address = newPk_address;
	}

	/**
	 * ����pk_entrust��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_entrust() {
		return pk_entrust;
	}

	/**
	 * ����pk_entrust��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_entrust
	 *            String
	 */
	public void setPk_entrust(String newPk_entrust) {
		this.pk_entrust = newPk_entrust;
	}

	/**
	 * ����pk_ent_line_b��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_ent_line_b() {
		return pk_ent_line_b;
	}

	/**
	 * ����pk_ent_line_b��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_ent_line_b
	 *            String
	 */
	public void setPk_ent_line_b(String newPk_ent_line_b) {
		this.pk_ent_line_b = newPk_ent_line_b;
	}

	/**
	 * ����dr��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����pk_city��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_city() {
		return pk_city;
	}

	/**
	 * ����pk_city��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_city
	 *            String
	 */
	public void setPk_city(String newPk_city) {
		this.pk_city = newPk_city;
	}

	public Integer getSerialno() {
		return serialno;
	}

	public void setSerialno(Integer serialno) {
		this.serialno = serialno;
	}

	/**
	 * ����contact��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * ����contact��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newContact
	 *            String
	 */
	public void setContact(String newContact) {
		this.contact = newContact;
	}

	/**
	 * ����pk_area��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_area() {
		return pk_area;
	}

	/**
	 * ����pk_area��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_area
	 *            String
	 */
	public void setPk_area(String newPk_area) {
		this.pk_area = newPk_area;
	}

	/**
	 * ����ts��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����pk_province��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getPk_province() {
		return pk_province;
	}

	/**
	 * ����pk_province��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newPk_province
	 *            String
	 */
	public void setPk_province(String newPk_province) {
		this.pk_province = newPk_province;
	}

	/**
	 * ����email��Getter����. ��������:2012-08-22 17:38:44
	 * 
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * ����email��Setter����. ��������:2012-08-22 17:38:44
	 * 
	 * @param newEmail
	 *            String
	 */
	public void setEmail(String newEmail) {
		this.email = newEmail;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-08-22 17:38:44
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_entrust";
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-08-22 17:38:44
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_ent_line_b";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-08-22 17:38:44
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_ent_line_b";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-08-22 17:38:44
	 */

	public UFDouble getMileage() {
		return mileage;
	}

	public UFDouble getCurr_longitude() {
		return curr_longitude;
	}

	public void setCurr_longitude(UFDouble curr_longitude) {
		this.curr_longitude = curr_longitude;
	}

	public UFDouble getCurr_latitude() {
		return curr_latitude;
	}

	public void setCurr_latitude(UFDouble curr_latitude) {
		this.curr_latitude = curr_latitude;
	}

	public void setMileage(UFDouble mileage) {
		this.mileage = mileage;
	}

	public String getApp_detail_addr() {
		return app_detail_addr;
	}

	public void setApp_detail_addr(String app_detail_addr) {
		this.app_detail_addr = app_detail_addr;
	}
	
	public List<EntLinePackBVO> getEntLinePackBVOs() {
		return EntLinePackBVOs;
	}

	public void setEntLinePackBVOs(List<EntLinePackBVO> entLinePackBVOs) {
		EntLinePackBVOs = entLinePackBVOs;
	}
	
	
	public String getOperate_name() {
		return operate_name;
	}

	public void setOperate_name(String operate_name) {
		this.operate_name = operate_name;
	}

	public EntLineBVO() {
		super();
	}
}
