/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.te;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDate;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 * <b> �ڴ˴���Ҫ�������Ĺ��� </b>
 * <p>
 * �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:2013-05-05 11:50:55
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class ExpAccidentVO extends SuperVO {
	private String invoice_vbillno;
	private String pk_psndoc;
	private UFBoolean carrier_flag;
	private String memo;
	private UFDateTime ts;
	private String reason_memo;
	private String reason_type;
	private String exp_type;
	private UFBoolean carr_claimant_flag;
	private String entrust_vbillno;
	private Integer exp_level;
	private String level_memo;
	private UFBoolean cust_claimant_flag;
	private String correct_measure;
	private Integer dr;
	private UFBoolean customer_flag;
	private String pk_exp_accident;
	private String pk_carrier;
	private String origin;
	private String longterm_measure;
	private String occur_addr;
	private UFDouble carr_claimant_amount;
	private Integer vbillstatus;
	private UFDateTime occur_date;
	private UFBoolean psndoc_flag;
	private UFDouble cust_claimant_amount;
	private String vbillno;
	private String fb_user;
	private UFDateTime fb_date;
	private String pk_corp;
	private String create_user;
	private UFDateTime create_time;
	private String pk_customer;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	private UFDateTime req_operate_time;
	private UFDateTime act_operate_time;
	private UFDouble exp_time;
	private UFDate dbilldate;
	private String modify_user;
	private UFDateTime modify_time;
	
	private UFBoolean upload_flag;
	private String exp_user;
	private String lot;

	public String getLot() {
		return lot;
	}

	public void setLot(String lot) {
		this.lot = lot;
	}

	public String getExp_user() {
		return exp_user;
	}

	public void setExp_user(String exp_user) {
		this.exp_user = exp_user;
	}

	public UFDateTime getReq_operate_time() {
		return req_operate_time;
	}

	public void setReq_operate_time(UFDateTime req_operate_time) {
		this.req_operate_time = req_operate_time;
	}

	public UFDateTime getAct_operate_time() {
		return act_operate_time;
	}

	public UFDateTime getFb_date() {
		return fb_date;
	}

	public void setFb_date(UFDateTime fb_date) {
		this.fb_date = fb_date;
	}

	public void setAct_operate_time(UFDateTime act_operate_time) {
		this.act_operate_time = act_operate_time;
	}

	public UFDouble getExp_time() {
		return exp_time;
	}

	public void setExp_time(UFDouble exp_time) {
		this.exp_time = exp_time;
	}

	public UFBoolean getUpload_flag() {
		return upload_flag;
	}

	public void setUpload_flag(UFBoolean upload_flag) {
		this.upload_flag = upload_flag;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	private UFDouble cust_unclaimant_amount;
	private UFDouble cust_claimanted_amount;
	private UFDouble carr_claimanted_amount;
	private UFDouble carr_unclaimant_amount;

	public static final String INVOICE_VBILLNO = "invoice_vbillno";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String CARRIER_FLAG = "carrier_flag";
	public static final String CUST_UNCLAIMANT_AMOUNT = "cust_unclaimant_amount";
	public static final String MEMO = "memo";
	public static final String REASON_MEMO = "reason_memo";
	public static final String REASON_TYPE = "reason_type";
	public static final String TYPE = "type";
	public static final String CARR_CLAIMANT_FLAG = "carr_claimant_flag";
	public static final String ENTRUST_VBILLNO = "entrust_vbillno";
	public static final String LEVEL = "level";
	public static final String LEVEL_MEMO = "level_memo";
	public static final String CREATE_DATE = "create_date";
	public static final String CUST_CLAIMANTED_AMOUNT = "cust_claimanted_amount";
	public static final String CUST_CLAIMANT_FLAG = "cust_claimant_flag";
	public static final String CORRECT_MEASURE = "correct_measure";
	public static final String CARR_UNCLAIMANT_AMOUNT = "carr_unclaimant_amount";
	public static final String CUSTOMER_FLAG = "customer_flag";
	public static final String PK_EXP_ACCIDENT = "pk_exp_accident";
	public static final String PK_CARRIER = "pk_carrier";
	public static final String ORIGIN = "origin";
	public static final String LONGTERM_MEASURE = "longterm_measure";
	public static final String OCCUR_ADDR = "occur_addr";
	public static final String CARR_CLAIMANT_AMOUNT = "carr_claimant_amount";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String OCCUR_DATE = "occur_date";
	public static final String PSNDOC_FLAG = "psndoc_flag";
	public static final String CARR_CLAIMANTED_AMOUNT = "carr_claimanted_amount";
	public static final String CUST_CLAIMANT_AMOUNT = "cust_claimant_amount";
	public static final String VBILLNO = "vbillno";
	public static final String CREATE_USER = "create_user";
	public static final String PK_CUSTOMER = "pk_customer";
	public static final String DBILLDATE = "dbilldate";

	public UFDate getDbilldate() {
		return dbilldate;
	}

	public void setDbilldate(UFDate dbilldate) {
		this.dbilldate = dbilldate;
	}

	public UFDouble getCust_unclaimant_amount() {
		return cust_unclaimant_amount;
	}

	public void setCust_unclaimant_amount(UFDouble cust_unclaimant_amount) {
		this.cust_unclaimant_amount = cust_unclaimant_amount;
	}

	public UFDouble getCust_claimanted_amount() {
		return cust_claimanted_amount;
	}

	public void setCust_claimanted_amount(UFDouble cust_claimanted_amount) {
		this.cust_claimanted_amount = cust_claimanted_amount;
	}

	public UFDouble getCarr_claimanted_amount() {
		return carr_claimanted_amount;
	}

	public void setCarr_claimanted_amount(UFDouble carr_claimanted_amount) {
		this.carr_claimanted_amount = carr_claimanted_amount;
	}

	public UFDouble getCarr_unclaimant_amount() {
		return carr_unclaimant_amount;
	}

	public void setCarr_unclaimant_amount(UFDouble carr_unclaimant_amount) {
		this.carr_unclaimant_amount = carr_unclaimant_amount;
	}

	/**
	 * ����invoice_vbillno��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getInvoice_vbillno() {
		return invoice_vbillno;
	}

	/**
	 * ����invoice_vbillno��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newInvoice_vbillno
	 *            String
	 */
	public void setInvoice_vbillno(String newInvoice_vbillno) {
		this.invoice_vbillno = newInvoice_vbillno;
	}

	/**
	 * ����pk_psndoc��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getPk_psndoc() {
		return pk_psndoc;
	}

	/**
	 * ����pk_psndoc��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newPk_psndoc
	 *            String
	 */
	public void setPk_psndoc(String newPk_psndoc) {
		this.pk_psndoc = newPk_psndoc;
	}

	/**
	 * ����carrier_flag��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getCarrier_flag() {
		return carrier_flag;
	}

	/**
	 * ����carrier_flag��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newCarrier_flag
	 *            UFBoolean
	 */
	public void setCarrier_flag(UFBoolean newCarrier_flag) {
		this.carrier_flag = newCarrier_flag;
	}

	/**
	 * ����memo��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����ts��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����reason_memo��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getReason_memo() {
		return reason_memo;
	}

	/**
	 * ����reason_memo��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newReason_memo
	 *            String
	 */
	public void setReason_memo(String newReason_memo) {
		this.reason_memo = newReason_memo;
	}

	/**
	 * ����reason_type��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getReason_type() {
		return reason_type;
	}

	/**
	 * ����reason_type��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newReason_type
	 *            String
	 */
	public void setReason_type(String newReason_type) {
		this.reason_type = newReason_type;
	}



	public String getExp_type() {
		return exp_type;
	}

	public void setExp_type(String exp_type) {
		this.exp_type = exp_type;
	}

	public Integer getExp_level() {
		return exp_level;
	}

	public void setExp_level(Integer exp_level) {
		this.exp_level = exp_level;
	}

	/**
	 * ����carr_claimant_flag��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getCarr_claimant_flag() {
		return carr_claimant_flag;
	}

	/**
	 * ����carr_claimant_flag��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newCarr_claimant_flag
	 *            UFBoolean
	 */
	public void setCarr_claimant_flag(UFBoolean newCarr_claimant_flag) {
		this.carr_claimant_flag = newCarr_claimant_flag;
	}

	/**
	 * ����entrust_vbillno��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getEntrust_vbillno() {
		return entrust_vbillno;
	}

	/**
	 * ����entrust_vbillno��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newEntrust_vbillno
	 *            String
	 */
	public void setEntrust_vbillno(String newEntrust_vbillno) {
		this.entrust_vbillno = newEntrust_vbillno;
	}


	/**
	 * ����level_memo��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getLevel_memo() {
		return level_memo;
	}

	/**
	 * ����level_memo��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newLevel_memo
	 *            String
	 */
	public void setLevel_memo(String newLevel_memo) {
		this.level_memo = newLevel_memo;
	}

	public String getFb_user() {
		return fb_user;
	}

	public void setFb_user(String fb_user) {
		this.fb_user = fb_user;
	}

	
	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	/**
	 * ����cust_claimant_flag��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getCust_claimant_flag() {
		return cust_claimant_flag;
	}

	/**
	 * ����cust_claimant_flag��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newCust_claimant_flag
	 *            UFBoolean
	 */
	public void setCust_claimant_flag(UFBoolean newCust_claimant_flag) {
		this.cust_claimant_flag = newCust_claimant_flag;
	}

	/**
	 * ����correct_measure��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getCorrect_measure() {
		return correct_measure;
	}

	/**
	 * ����correct_measure��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newCorrect_measure
	 *            String
	 */
	public void setCorrect_measure(String newCorrect_measure) {
		this.correct_measure = newCorrect_measure;
	}

	/**
	 * ����dr��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����customer_flag��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getCustomer_flag() {
		return customer_flag;
	}

	/**
	 * ����customer_flag��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newCustomer_flag
	 *            UFBoolean
	 */
	public void setCustomer_flag(UFBoolean newCustomer_flag) {
		this.customer_flag = newCustomer_flag;
	}

	/**
	 * ����pk_exp_accident��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getPk_exp_accident() {
		return pk_exp_accident;
	}

	/**
	 * ����pk_exp_accident��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newPk_exp_accident
	 *            String
	 */
	public void setPk_exp_accident(String newPk_exp_accident) {
		this.pk_exp_accident = newPk_exp_accident;
	}

	/**
	 * ����pk_carrier��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getPk_carrier() {
		return pk_carrier;
	}

	/**
	 * ����pk_carrier��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newPk_carrier
	 *            String
	 */
	public void setPk_carrier(String newPk_carrier) {
		this.pk_carrier = newPk_carrier;
	}

	/**
	 * ����origin��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getOrigin() {
		return origin;
	}

	/**
	 * ����origin��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newOrigin
	 *            String
	 */
	public void setOrigin(String newOrigin) {
		this.origin = newOrigin;
	}

	/**
	 * ����longterm_measure��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getLongterm_measure() {
		return longterm_measure;
	}

	/**
	 * ����longterm_measure��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newLongterm_measure
	 *            String
	 */
	public void setLongterm_measure(String newLongterm_measure) {
		this.longterm_measure = newLongterm_measure;
	}

	/**
	 * ����occur_addr��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getOccur_addr() {
		return occur_addr;
	}

	/**
	 * ����occur_addr��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newOccur_addr
	 *            String
	 */
	public void setOccur_addr(String newOccur_addr) {
		this.occur_addr = newOccur_addr;
	}

	/**
	 * ����carr_claimant_amount��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return UFDouble
	 */
	public UFDouble getCarr_claimant_amount() {
		return carr_claimant_amount;
	}

	/**
	 * ����carr_claimant_amount��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newCarr_claimant_amount
	 *            UFDouble
	 */
	public void setCarr_claimant_amount(UFDouble newCarr_claimant_amount) {
		this.carr_claimant_amount = newCarr_claimant_amount;
	}

	/**
	 * ����vbillstatus��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * ����vbillstatus��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {
		this.vbillstatus = newVbillstatus;
	}

	public UFBoolean getPsndoc_flag() {
		return psndoc_flag;
	}

	public UFDateTime getOccur_date() {
		return occur_date;
	}

	public void setOccur_date(UFDateTime occur_date) {
		this.occur_date = occur_date;
	}

	/**
	 * ����psndoc_flag��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newPsndoc_flag
	 *            UFBoolean
	 */
	public void setPsndoc_flag(UFBoolean newPsndoc_flag) {
		this.psndoc_flag = newPsndoc_flag;
	}

	/**
	 * ����cust_claimant_amount��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return UFDouble
	 */
	public UFDouble getCust_claimant_amount() {
		return cust_claimant_amount;
	}

	/**
	 * ����cust_claimant_amount��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newCust_claimant_amount
	 *            UFDouble
	 */
	public void setCust_claimant_amount(UFDouble newCust_claimant_amount) {
		this.cust_claimant_amount = newCust_claimant_amount;
	}

	/**
	 * ����vbillno��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * ����vbillno��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {
		this.vbillno = newVbillno;
	}

	/**
	 * ����create_user��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getCreate_user() {
		return create_user;
	}

	/**
	 * ����create_user��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newCreate_user
	 *            String
	 */
	public void setCreate_user(String newCreate_user) {
		this.create_user = newCreate_user;
	}

	/**
	 * ����pk_customer��Getter����. ��������:2013-05-05 11:50:55
	 * 
	 * @return String
	 */
	public String getPk_customer() {
		return pk_customer;
	}

	/**
	 * ����pk_customer��Setter����. ��������:2013-05-05 11:50:55
	 * 
	 * @param newPk_customer
	 *            String
	 */
	public void setPk_customer(String newPk_customer) {
		this.pk_customer = newPk_customer;
	}

	/**
	 * <p>
	 * ȡ�ø�VO����ֶ�.
	 * <p>
	 * ��������:2013-05-05 11:50:55
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ����.
	 * <p>
	 * ��������:2013-05-05 11:50:55
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_exp_accident";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2013-05-05 11:50:55
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_exp_accident";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2013-05-05 11:50:55
	 */
	public ExpAccidentVO() {
		super();
	}
}
