/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.jf.vo;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDateTime;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2012-02-10 14:32:38
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class BillTempletVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String nodecode;
	private String metadataclass;
	private String bill_templetname;
	private String pk_billtemplet;
	private String bill_templetcaption;
	private String pk_billtypecode;
	private String options;
	private String resid;
	private UFBoolean shareflag;
	private UFBoolean model_type;
	private Integer dr;
	private String validateformula;
	private UFDateTime create_time;
	private String create_user;
	private UFDateTime modify_time;
	private String modify_user;

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public static final String PK_CORP = "pk_corp";
	public static final String NODECODE = "nodecode";
	public static final String METADATACLASS = "metadataclass";
	public static final String BILL_TEMPLETNAME = "bill_templetname";
	public static final String PK_BILLTEMPLET = "pk_billtemplet";
	public static final String BILL_TEMPLETCAPTION = "bill_templetcaption";
	public static final String PK_BILLTYPECODE = "pk_billtypecode";
	public static final String OPTIONS = "options";
	public static final String RESID = "resid";
	public static final String SHAREFLAG = "shareflag";
	public static final String MODEL_TYPE = "model_type";
	public static final String VALIDATEFORMULA = "validateformula";

	/**
	 * 属性pk_corp的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * 属性nodecode的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getNodecode() {
		return nodecode;
	}

	/**
	 * 属性nodecode的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newNodecode
	 *            String
	 */
	public void setNodecode(String newNodecode) {
		this.nodecode = newNodecode;
	}

	/**
	 * 属性metadataclass的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getMetadataclass() {
		return metadataclass;
	}

	/**
	 * 属性metadataclass的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newMetadataclass
	 *            String
	 */
	public void setMetadataclass(String newMetadataclass) {
		this.metadataclass = newMetadataclass;
	}

	/**
	 * 属性bill_templetname的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getBill_templetname() {
		return bill_templetname;
	}

	/**
	 * 属性bill_templetname的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newBill_templetname
	 *            String
	 */
	public void setBill_templetname(String newBill_templetname) {
		this.bill_templetname = newBill_templetname;
	}

	/**
	 * 属性pk_billtemplet的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getPk_billtemplet() {
		return pk_billtemplet;
	}

	/**
	 * 属性pk_billtemplet的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newPk_billtemplet
	 *            String
	 */
	public void setPk_billtemplet(String newPk_billtemplet) {
		this.pk_billtemplet = newPk_billtemplet;
	}

	/**
	 * 属性bill_templetcaption的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getBill_templetcaption() {
		return bill_templetcaption;
	}

	/**
	 * 属性bill_templetcaption的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newBill_templetcaption
	 *            String
	 */
	public void setBill_templetcaption(String newBill_templetcaption) {
		this.bill_templetcaption = newBill_templetcaption;
	}

	/**
	 * 属性pk_billtypecode的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getPk_billtypecode() {
		return pk_billtypecode;
	}

	/**
	 * 属性pk_billtypecode的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newPk_billtypecode
	 *            String
	 */
	public void setPk_billtypecode(String newPk_billtypecode) {
		this.pk_billtypecode = newPk_billtypecode;
	}

	/**
	 * 属性options的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getOptions() {
		return options;
	}

	/**
	 * 属性options的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newOptions
	 *            String
	 */
	public void setOptions(String newOptions) {
		this.options = newOptions;
	}

	/**
	 * 属性resid的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getResid() {
		return resid;
	}

	/**
	 * 属性resid的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newResid
	 *            String
	 */
	public void setResid(String newResid) {
		this.resid = newResid;
	}

	/**
	 * 属性shareflag的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getShareflag() {
		return shareflag;
	}

	/**
	 * 属性shareflag的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newShareflag
	 *            UFBoolean
	 */
	public void setShareflag(UFBoolean newShareflag) {
		this.shareflag = newShareflag;
	}

	/**
	 * 属性model_type的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getModel_type() {
		return model_type;
	}

	/**
	 * 属性model_type的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newModel_type
	 *            UFBoolean
	 */
	public void setModel_type(UFBoolean newModel_type) {
		this.model_type = newModel_type;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性validateformula的Getter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @return String
	 */
	public String getValidateformula() {
		return validateformula;
	}

	/**
	 * 属性validateformula的Setter方法. 创建日期:2012-02-10 14:32:38
	 * 
	 * @param newValidateformula
	 *            String
	 */
	public void setValidateformula(String newValidateformula) {
		this.validateformula = newValidateformula;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-02-10 14:32:38
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-02-10 14:32:38
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_billtemplet";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-02-10 14:32:38
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_billtemplet";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-02-10 14:32:38
	 */
	public BillTempletVO() {
		super();
	}
}
