/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package org.nw.jf.vo;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFDateTime;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-04-30 10:39:37
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PrintTempletVO extends SuperVO {
	private String nodecode;
	private String vtemplatename;
	private String vtemplatecode;
	private String pk_corp;
	private UFDateTime ts;
	private String pk_print_templet;
	private Integer dr;
	private String file_name;
	private String memo;
	private String create_user;
	private UFDateTime create_time;
	private Long file_size;
	private Long ori_file_size;
	private String head_formula;
	private String body_formula;
	private UFDateTime modify_time;
	private String modify_user;
	private String datasourcesql;

	public UFDateTime getModify_time() {
		return modify_time;
	}

	public void setModify_time(UFDateTime modify_time) {
		this.modify_time = modify_time;
	}

	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}

	public static final String NODECODE = "nodecode";
	public static final String VTEMPLATENAME = "vtemplatename";
	public static final String VTEMPLATECODE = "vtemplatecode";
	public static final String PK_CORP = "pk_corp";
	public static final String PK_PRINT_TEMPLET = "pk_print_templet";
	public static final String FILE_NAME = "file_name";
	public static final String MEMO = "memo";
	public static final String CREATE_USER = "create_user";
	public static final String CREATE_TIME = "create_time";
	public static final String FILE_SIZE = "file_size";
	public static final String ORI_FILE_SIZE = "ori_file_size";

	public String getHead_formula() {
		return head_formula;
	}

	public void setHead_formula(String head_formula) {
		this.head_formula = head_formula;
	}

	public String getBody_formula() {
		return body_formula;
	}

	public void setBody_formula(String body_formula) {
		this.body_formula = body_formula;
	}

	public Long getOri_file_size() {
		return ori_file_size;
	}

	public void setOri_file_size(Long ori_file_size) {
		this.ori_file_size = ori_file_size;
	}

	public String getVtemplatecode() {
		return vtemplatecode;
	}

	public void setVtemplatecode(String vtemplatecode) {
		this.vtemplatecode = vtemplatecode;
	}

	public String getFile_name() {
		return file_name;
	}

	public void setFile_name(String file_name) {
		this.file_name = file_name;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public UFDateTime getCreate_time() {
		return create_time;
	}

	public void setCreate_time(UFDateTime create_time) {
		this.create_time = create_time;
	}

	public Long getFile_size() {
		return file_size;
	}

	public void setFile_size(Long file_size) {
		this.file_size = file_size;
	}

	/**
	 * 属性nodecode的Getter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @return String
	 */
	public String getNodecode() {
		return nodecode;
	}

	/**
	 * 属性nodecode的Setter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @param newNodecode
	 *            String
	 */
	public void setNodecode(String newNodecode) {
		this.nodecode = newNodecode;
	}

	/**
	 * 属性vtemplatename的Getter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @return String
	 */
	public String getVtemplatename() {
		return vtemplatename;
	}

	/**
	 * 属性vtemplatename的Setter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @param newVtemplatename
	 *            String
	 */
	public void setVtemplatename(String newVtemplatename) {
		this.vtemplatename = newVtemplatename;
	}

	/**
	 * 属性pk_corp的Getter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * 属性pk_print_templet的Getter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @return String
	 */
	public String getPk_print_templet() {
		return pk_print_templet;
	}

	/**
	 * 属性pk_print_templet的Setter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @param newPk_print_templet
	 *            String
	 */
	public void setPk_print_templet(String newPk_print_templet) {
		this.pk_print_templet = newPk_print_templet;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2013-04-30 10:39:37
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}
	

	public String getDatasourcesql() {
		return datasourcesql;
	}

	public void setDatasourcesql(String datasourcesql) {
		this.datasourcesql = datasourcesql;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2013-04-30 10:39:37
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2013-04-30 10:39:37
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_print_templet";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2013-04-30 10:39:37
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "nw_print_templet";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2013-04-30 10:39:37
	 */
	public PrintTempletVO() {
		super();
	}
}
