/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.cm;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDate;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 */
@SuppressWarnings("serial")
public class ContractBVO extends SuperVO {
	private UFDouble interval10;
	private Integer quote_type;
	private UFDouble lowest_fee;
	private UFDouble interval7;
	private String start_addr;
	private UFDouble price5;
	private UFDouble interval8;
	private UFDouble price8;
	private UFDouble price10;
	private Integer dr;
	private UFDouble interval5;
	private String pk_expense_type;
	private Integer start_addr_type;
	private UFDouble price2;
	private UFDate invalid_date;
	private Integer end_addr_type;
	private UFDateTime ts;
	private UFDouble interval12;
	private Integer valuation_type;
	private String equip_type;
	private UFDouble price6;
	private UFDouble interval3;
	private UFDouble interval6;
	private UFDouble price11;
	private UFDouble interval11;
	private String pk_contract;
	private UFDouble price7;
	private UFDouble interval2;
	private UFBoolean locked_flag;
	private UFDouble interval1;
	private UFDouble price1;
	private UFDouble interval9;
	private UFDouble price9;
	private UFDouble interval4;
	private Integer price_type;
	private UFDouble price3;
	private UFDate effective_date;
	private UFDouble price12;
	private UFDouble first_weight_price;
	private UFDouble first_weight_cost;
	private UFDouble first_weight;
	private UFDouble lowest_cost;
	private String end_addr;
	private UFDouble price4;
	private UFDouble cost1;
	private UFDouble cost2;
	private UFDouble cost3;
	private UFDouble cost4;
	private UFDouble cost5;
	private UFDouble cost6;
	private UFDouble cost7;
	private UFDouble cost8;
	private UFDouble cost9;
	private UFDouble cost10;
	private UFDouble cost11;
	private UFDouble cost12;
	private String pk_contract_b;
	private Integer parent_type;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	private Integer tax_cat;
	private UFDouble tax_rate;
	private String memo;
	// 2015-06-01 增加自定义算法和是否回程
	private String custom_proc;
	private UFBoolean if_return;
	
	private UFBoolean if_optional;
	
	private Integer urgent_level;
	private String item_code;
	private String pk_trans_line;
	private String pack;
	
	public UFDouble getLowest_cost() {
		return lowest_cost;
	}

	public void setLowest_cost(UFDouble lowest_cost) {
		this.lowest_cost = lowest_cost;
	}

	public UFDouble getCost1() {
		return cost1;
	}

	public void setCost1(UFDouble cost1) {
		this.cost1 = cost1;
	}

	public UFDouble getCost2() {
		return cost2;
	}

	public void setCost2(UFDouble cost2) {
		this.cost2 = cost2;
	}

	public Integer getParent_type() {
		return parent_type;
	}

	public void setParent_type(Integer parent_type) {
		this.parent_type = parent_type;
	}

	public UFDouble getCost3() {
		return cost3;
	}

	public void setCost3(UFDouble cost3) {
		this.cost3 = cost3;
	}

	public UFDouble getCost4() {
		return cost4;
	}

	public void setCost4(UFDouble cost4) {
		this.cost4 = cost4;
	}

	public UFDouble getCost5() {
		return cost5;
	}

	public void setCost5(UFDouble cost5) {
		this.cost5 = cost5;
	}

	public UFDouble getCost6() {
		return cost6;
	}

	public void setCost6(UFDouble cost6) {
		this.cost6 = cost6;
	}

	public UFDouble getCost7() {
		return cost7;
	}

	public void setCost7(UFDouble cost7) {
		this.cost7 = cost7;
	}

	public UFDouble getCost8() {
		return cost8;
	}

	public void setCost8(UFDouble cost8) {
		this.cost8 = cost8;
	}

	public UFDouble getCost9() {
		return cost9;
	}

	public void setCost9(UFDouble cost9) {
		this.cost9 = cost9;
	}

	public UFDouble getCost10() {
		return cost10;
	}

	public void setCost10(UFDouble cost10) {
		this.cost10 = cost10;
	}

	public UFDouble getCost11() {
		return cost11;
	}

	public void setCost11(UFDouble cost11) {
		this.cost11 = cost11;
	}

	public UFDouble getCost12() {
		return cost12;
	}

	public void setCost12(UFDouble cost12) {
		this.cost12 = cost12;
	}

	public String getPack() {
		return pack;
	}

	public void setPack(String pack) {
		this.pack = pack;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public UFDouble getFirst_weight_cost() {
		return first_weight_cost;
	}

	public void setFirst_weight_cost(UFDouble first_weight_cost) {
		this.first_weight_cost = first_weight_cost;
	}

	public UFBoolean getIf_optional() {
		return if_optional;
	}

	public void setIf_optional(UFBoolean if_optional) {
		this.if_optional = if_optional;
	}

	public Integer getUrgent_level() {
		return urgent_level;
	}

	public void setUrgent_level(Integer urgent_level) {
		this.urgent_level = urgent_level;
	}

	public String getItem_code() {
		return item_code;
	}

	public void setItem_code(String item_code) {
		this.item_code = item_code;
	}

	public String getPk_trans_line() {
		return pk_trans_line;
	}

	public void setPk_trans_line(String pk_trans_line) {
		this.pk_trans_line = pk_trans_line;
	}

	public Integer getTax_cat() {
		return tax_cat;
	}

	public void setTax_cat(Integer tax_cat) {
		this.tax_cat = tax_cat;
	}

	public UFDouble getTax_rate() {
		return tax_rate;
	}

	public void setTax_rate(UFDouble tax_rate) {
		this.tax_rate = tax_rate;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String INTERVAL10 = "interval10";
	public static final String QUOTE_TYPE = "quote_type";
	public static final String LOWEST_FEE = "lowest_fee";
	public static final String INTERVAL7 = "interval7";
	public static final String START_ADDR = "start_addr";
	public static final String PRICE5 = "price5";
	public static final String INTERVAL8 = "interval8";
	public static final String PRICE8 = "price8";
	public static final String PRICE10 = "price10";
	public static final String INTERVAL5 = "interval5";
	public static final String PK_EXPENSE_TYPE = "pk_expense_type";
	public static final String START_ADDR_TYPE = "start_addr_type";
	public static final String PRICE2 = "price2";
	public static final String INVALID_DATE = "invalid_date";
	public static final String END_ADDR_TYPE = "end_addr_type";
	public static final String INTERVAL12 = "interval12";
	public static final String VALUATION_TYPE = "valuation_type";
	public static final String EQUIP_TYPE = "equip_type";
	public static final String PRICE6 = "price6";
	public static final String INTERVAL3 = "interval3";
	public static final String INTERVAL6 = "interval6";
	public static final String PRICE11 = "price11";
	public static final String INTERVAL11 = "interval11";
	public static final String PK_CONTRACT = "pk_contract";
	public static final String PRICE7 = "price7";
	public static final String INTERVAL2 = "interval2";
	public static final String LOCKED_FLAG = "locked_flag";
	public static final String INTERVAL1 = "interval1";
	public static final String PRICE1 = "price1";
	public static final String INTERVAL9 = "interval9";
	public static final String PRICE9 = "price9";
	public static final String INTERVAL4 = "interval4";
	public static final String PRICE_TYPE = "price_type";
	public static final String PRICE3 = "price3";
	public static final String EFFECTIVE_DATE = "effective_date";
	public static final String PRICE12 = "price12";
	public static final String FIRST_WEIGHT_PRICE = "first_weight_price";
	public static final String FIRST_WEIGHT = "first_weight";
	public static final String END_ADDR = "end_addr";
	public static final String PRICE4 = "price4";
	public static final String PK_CONTRACT_B = "pk_contract_b";
	public static final String CUSTOM_PROC = "custom_proc";
	public static final String IF_RETURN = "if_return";

	public String getCustom_proc() {
		return custom_proc;
	}

	public void setCustom_proc(String custom_proc) {
		this.custom_proc = custom_proc;
	}

	public UFBoolean getIf_return() {
		return if_return;
	}

	public void setIf_return(UFBoolean if_return) {
		this.if_return = if_return;
	}

	public String getEquip_type() {
		return equip_type;
	}

	public void setEquip_type(String equip_type) {
		this.equip_type = equip_type;
	}

	/**
	 * ����interval10��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval10() {
		return interval10;
	}

	/**
	 * ����interval10��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval10
	 *            UFDouble
	 */
	public void setInterval10(UFDouble newInterval10) {
		this.interval10 = newInterval10;
	}

	/**
	 * ����quote_type��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return Integer
	 */
	public Integer getQuote_type() {
		return quote_type;
	}

	/**
	 * ����quote_type��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newQuote_type
	 *            Integer
	 */
	public void setQuote_type(Integer newQuote_type) {
		this.quote_type = newQuote_type;
	}

	/**
	 * ����lowest_fee��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getLowest_fee() {
		return lowest_fee;
	}

	/**
	 * ����lowest_fee��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newLowest_fee
	 *            UFDouble
	 */
	public void setLowest_fee(UFDouble newLowest_fee) {
		this.lowest_fee = newLowest_fee;
	}

	/**
	 * ����interval7��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval7() {
		return interval7;
	}

	/**
	 * ����interval7��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval7
	 *            UFDouble
	 */
	public void setInterval7(UFDouble newInterval7) {
		this.interval7 = newInterval7;
	}

	/**
	 * ����start_addr��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return String
	 */
	public String getStart_addr() {
		return start_addr;
	}

	/**
	 * ����start_addr��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newStart_addr
	 *            String
	 */
	public void setStart_addr(String newStart_addr) {
		this.start_addr = newStart_addr;
	}

	/**
	 * ����price5��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice5() {
		return price5;
	}

	/**
	 * ����price5��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice5
	 *            UFDouble
	 */
	public void setPrice5(UFDouble newPrice5) {
		this.price5 = newPrice5;
	}

	/**
	 * ����interval8��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval8() {
		return interval8;
	}

	/**
	 * ����interval8��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval8
	 *            UFDouble
	 */
	public void setInterval8(UFDouble newInterval8) {
		this.interval8 = newInterval8;
	}

	/**
	 * ����price8��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice8() {
		return price8;
	}

	/**
	 * ����price8��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice8
	 *            UFDouble
	 */
	public void setPrice8(UFDouble newPrice8) {
		this.price8 = newPrice8;
	}

	/**
	 * ����price10��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice10() {
		return price10;
	}

	/**
	 * ����price10��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice10
	 *            UFDouble
	 */
	public void setPrice10(UFDouble newPrice10) {
		this.price10 = newPrice10;
	}

	/**
	 * ����dr��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����interval5��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval5() {
		return interval5;
	}

	/**
	 * ����interval5��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval5
	 *            UFDouble
	 */
	public void setInterval5(UFDouble newInterval5) {
		this.interval5 = newInterval5;
	}

	/**
	 * ����pk_expense_type��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return String
	 */
	public String getPk_expense_type() {
		return pk_expense_type;
	}

	/**
	 * ����pk_expense_type��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPk_expense_type
	 *            String
	 */
	public void setPk_expense_type(String newPk_expense_type) {
		this.pk_expense_type = newPk_expense_type;
	}

	/**
	 * ����price2��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice2() {
		return price2;
	}

	/**
	 * ����price2��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice2
	 *            UFDouble
	 */
	public void setPrice2(UFDouble newPrice2) {
		this.price2 = newPrice2;
	}

	/**
	 * ����invalid_date��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDate
	 */
	public UFDate getInvalid_date() {
		return invalid_date;
	}

	/**
	 * ����invalid_date��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInvalid_date
	 *            UFDate
	 */
	public void setInvalid_date(UFDate newInvalid_date) {
		this.invalid_date = newInvalid_date;
	}

	public Integer getStart_addr_type() {
		return start_addr_type;
	}

	public void setStart_addr_type(Integer start_addr_type) {
		this.start_addr_type = start_addr_type;
	}

	public Integer getEnd_addr_type() {
		return end_addr_type;
	}

	public void setEnd_addr_type(Integer end_addr_type) {
		this.end_addr_type = end_addr_type;
	}

	/**
	 * ����ts��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����interval12��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval12() {
		return interval12;
	}

	/**
	 * ����interval12��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval12
	 *            UFDouble
	 */
	public void setInterval12(UFDouble newInterval12) {
		this.interval12 = newInterval12;
	}

	/**
	 * ����valuation_type��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return Integer
	 */
	public Integer getValuation_type() {
		return valuation_type;
	}

	/**
	 * ����valuation_type��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newValuation_type
	 *            Integer
	 */
	public void setValuation_type(Integer newValuation_type) {
		this.valuation_type = newValuation_type;
	}

	/**
	 * ����price6��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice6() {
		return price6;
	}

	/**
	 * ����price6��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice6
	 *            UFDouble
	 */
	public void setPrice6(UFDouble newPrice6) {
		this.price6 = newPrice6;
	}

	/**
	 * ����interval3��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval3() {
		return interval3;
	}

	/**
	 * ����interval3��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval3
	 *            UFDouble
	 */
	public void setInterval3(UFDouble newInterval3) {
		this.interval3 = newInterval3;
	}

	/**
	 * ����interval6��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval6() {
		return interval6;
	}

	/**
	 * ����interval6��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval6
	 *            UFDouble
	 */
	public void setInterval6(UFDouble newInterval6) {
		this.interval6 = newInterval6;
	}

	/**
	 * ����price11��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice11() {
		return price11;
	}

	/**
	 * ����price11��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice11
	 *            UFDouble
	 */
	public void setPrice11(UFDouble newPrice11) {
		this.price11 = newPrice11;
	}

	/**
	 * ����interval11��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval11() {
		return interval11;
	}

	/**
	 * ����interval11��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval11
	 *            UFDouble
	 */
	public void setInterval11(UFDouble newInterval11) {
		this.interval11 = newInterval11;
	}

	/**
	 * ����pk_contract��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return String
	 */
	public String getPk_contract() {
		return pk_contract;
	}

	/**
	 * ����pk_contract��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPk_contract
	 *            String
	 */
	public void setPk_contract(String newPk_contract) {
		this.pk_contract = newPk_contract;
	}

	/**
	 * ����price7��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice7() {
		return price7;
	}

	/**
	 * ����price7��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice7
	 *            UFDouble
	 */
	public void setPrice7(UFDouble newPrice7) {
		this.price7 = newPrice7;
	}

	/**
	 * ����interval2��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval2() {
		return interval2;
	}

	/**
	 * ����interval2��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval2
	 *            UFDouble
	 */
	public void setInterval2(UFDouble newInterval2) {
		this.interval2 = newInterval2;
	}

	/**
	 * ����locked_flag��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getLocked_flag() {
		return locked_flag;
	}

	/**
	 * ����locked_flag��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newLocked_flag
	 *            UFBoolean
	 */
	public void setLocked_flag(UFBoolean newLocked_flag) {
		this.locked_flag = newLocked_flag;
	}

	/**
	 * ����interval1��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval1() {
		return interval1;
	}

	/**
	 * ����interval1��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval1
	 *            UFDouble
	 */
	public void setInterval1(UFDouble newInterval1) {
		this.interval1 = newInterval1;
	}

	/**
	 * ����price1��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice1() {
		return price1;
	}

	/**
	 * ����price1��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice1
	 *            UFDouble
	 */
	public void setPrice1(UFDouble newPrice1) {
		this.price1 = newPrice1;
	}

	/**
	 * ����interval9��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval9() {
		return interval9;
	}

	/**
	 * ����interval9��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval9
	 *            UFDouble
	 */
	public void setInterval9(UFDouble newInterval9) {
		this.interval9 = newInterval9;
	}

	/**
	 * ����price9��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice9() {
		return price9;
	}

	/**
	 * ����price9��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice9
	 *            UFDouble
	 */
	public void setPrice9(UFDouble newPrice9) {
		this.price9 = newPrice9;
	}

	/**
	 * ����interval4��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getInterval4() {
		return interval4;
	}

	/**
	 * ����interval4��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newInterval4
	 *            UFDouble
	 */
	public void setInterval4(UFDouble newInterval4) {
		this.interval4 = newInterval4;
	}

	/**
	 * ����price_type��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return Integer
	 */
	public Integer getPrice_type() {
		return price_type;
	}

	/**
	 * ����price_type��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice_type
	 *            Integer
	 */
	public void setPrice_type(Integer newPrice_type) {
		this.price_type = newPrice_type;
	}

	/**
	 * ����price3��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice3() {
		return price3;
	}

	/**
	 * ����price3��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice3
	 *            UFDouble
	 */
	public void setPrice3(UFDouble newPrice3) {
		this.price3 = newPrice3;
	}

	/**
	 * ����effective_date��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDate
	 */
	public UFDate getEffective_date() {
		return effective_date;
	}

	/**
	 * ����effective_date��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newEffective_date
	 *            UFDate
	 */
	public void setEffective_date(UFDate newEffective_date) {
		this.effective_date = newEffective_date;
	}

	/**
	 * ����price12��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice12() {
		return price12;
	}

	/**
	 * ����price12��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice12
	 *            UFDouble
	 */
	public void setPrice12(UFDouble newPrice12) {
		this.price12 = newPrice12;
	}

	/**
	 * ����first_weight_price��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getFirst_weight_price() {
		return first_weight_price;
	}

	/**
	 * ����first_weight_price��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newFirst_weight_price
	 *            UFDouble
	 */
	public void setFirst_weight_price(UFDouble newFirst_weight_price) {
		this.first_weight_price = newFirst_weight_price;
	}

	/**
	 * ����first_weight��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getFirst_weight() {
		return first_weight;
	}

	/**
	 * ����first_weight��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newFirst_weight
	 *            UFDouble
	 */
	public void setFirst_weight(UFDouble newFirst_weight) {
		this.first_weight = newFirst_weight;
	}

	/**
	 * ����end_addr��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return String
	 */
	public String getEnd_addr() {
		return end_addr;
	}

	/**
	 * ����end_addr��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newEnd_addr
	 *            String
	 */
	public void setEnd_addr(String newEnd_addr) {
		this.end_addr = newEnd_addr;
	}

	/**
	 * ����price4��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice4() {
		return price4;
	}

	/**
	 * ����price4��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPrice4
	 *            UFDouble
	 */
	public void setPrice4(UFDouble newPrice4) {
		this.price4 = newPrice4;
	}

	/**
	 * ����pk_contract_b��Getter����. ��������:2012-08-28 21:28:00
	 * 
	 * @return String
	 */
	public String getPk_contract_b() {
		return pk_contract_b;
	}

	/**
	 * ����pk_contract_b��Setter����. ��������:2012-08-28 21:28:00
	 * 
	 * @param newPk_contract_b
	 *            String
	 */
	public void setPk_contract_b(String newPk_contract_b) {
		this.pk_contract_b = newPk_contract_b;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-08-28 21:28:00
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_contract";
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-08-28 21:28:00
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_contract_b";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-08-28 21:28:00
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_contract_b";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-08-28 21:28:00
	 */
	public ContractBVO() {
		super();
	}
}
