/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.cm;

import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 * <b> �ڴ˴���Ҫ��������Ĺ��� </b>
 * <p>
 * �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:2012-08-28 21:27:29
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class ExpenseTypeVO extends SuperVO {
	private String pk_corp;
	private String code;
	private String memo;
	private UFBoolean locked_flag;
	private Integer expense_type;
	private UFDateTime ts;
	private Integer dr;
	private String pk_expense_type;
	private String name;
	private UFBoolean if_preset;// 是否预置
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	
	private Integer operation_type;
	

	public Integer getOperation_type() {
		return operation_type;
	}

	public void setOperation_type(Integer operation_type) {
		this.operation_type = operation_type;
	}

	// 2015-05-30
	private Integer parent_type;

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String PK_CORP = "pk_corp";
	public static final String CODE = "code";
	public static final String MEMO = "memo";
	public static final String LOCKED_FLAG = "locked_flag";
	public static final String TYPE = "type";
	public static final String PK_EXPENSE_TYPE = "pk_expense_type";
	public static final String NAME = "name";
	public static final String IF_PRESET = "if_preset";
	public static final String PARENT_TYPE = "parent_type";

	public Integer getParent_type() {
		return parent_type;
	}

	public void setParent_type(Integer parent_type) {
		this.parent_type = parent_type;
	}

	public UFBoolean getIf_preset() {
		return if_preset;
	}

	public void setIf_preset(UFBoolean if_preset) {
		this.if_preset = if_preset;
	}

	/**
	 * ����pk_corp��Getter����. ��������:2012-08-28 21:27:29
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * ����pk_corp��Setter����. ��������:2012-08-28 21:27:29
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * ����code��Getter����. ��������:2012-08-28 21:27:29
	 * 
	 * @return String
	 */
	public String getCode() {
		return code;
	}

	/**
	 * ����code��Setter����. ��������:2012-08-28 21:27:29
	 * 
	 * @param newCode
	 *            String
	 */
	public void setCode(String newCode) {
		this.code = newCode;
	}

	/**
	 * ����memo��Getter����. ��������:2012-08-28 21:27:29
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ����memo��Setter����. ��������:2012-08-28 21:27:29
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * ����locked_flag��Getter����. ��������:2012-08-28 21:27:29
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getLocked_flag() {
		return locked_flag;
	}

	/**
	 * ����locked_flag��Setter����. ��������:2012-08-28 21:27:29
	 * 
	 * @param newLocked_flag
	 *            UFBoolean
	 */
	public void setLocked_flag(UFBoolean newLocked_flag) {
		this.locked_flag = newLocked_flag;
	}


	public Integer getExpense_type() {
		return expense_type;
	}

	public void setExpense_type(Integer expense_type) {
		this.expense_type = expense_type;
	}

	/**
	 * ����ts��Getter����. ��������:2012-08-28 21:27:29
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * ����ts��Setter����. ��������:2012-08-28 21:27:29
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * ����dr��Getter����. ��������:2012-08-28 21:27:29
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * ����dr��Setter����. ��������:2012-08-28 21:27:29
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * ����pk_expense_type��Getter����. ��������:2012-08-28 21:27:29
	 * 
	 * @return String
	 */
	public String getPk_expense_type() {
		return pk_expense_type;
	}

	/**
	 * ����pk_expense_type��Setter����. ��������:2012-08-28 21:27:29
	 * 
	 * @param newPk_expense_type
	 *            String
	 */
	public void setPk_expense_type(String newPk_expense_type) {
		this.pk_expense_type = newPk_expense_type;
	}

	/**
	 * ����name��Getter����. ��������:2012-08-28 21:27:29
	 * 
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/**
	 * ����name��Setter����. ��������:2012-08-28 21:27:29
	 * 
	 * @param newName
	 *            String
	 */
	public void setName(String newName) {
		this.name = newName;
	}

	/**
	 * <p>
	 * ȡ�ø�VO�����ֶ�.
	 * <p>
	 * ��������:2012-08-28 21:27:29
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * ȡ�ñ�����.
	 * <p>
	 * ��������:2012-08-28 21:27:29
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_expense_type";
	}

	/**
	 * <p>
	 * ���ر����.
	 * <p>
	 * ��������:2012-08-28 21:27:29
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_expense_type";
	}

	/**
	 * ����Ĭ�Ϸ�ʽ����������.
	 * 
	 * ��������:2012-08-28 21:27:29
	 */
	public ExpenseTypeVO() {
		super();
	}
}
