/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.tms.vo.cm;

import org.nw.annotation.NotDBField;
import org.nw.vo.pub.SuperVO;
import org.nw.vo.pub.lang.UFBoolean;
import org.nw.vo.pub.lang.UFDateTime;
import org.nw.vo.pub.lang.UFDouble;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2012-08-09 23:48:22
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class ReceDetailBVO extends SuperVO {
	private String pk_receive_detail;
	private String pk_rece_detail_b;
	private String memo;
	private Integer quote_type;
	private Integer dr;
	private String pk_expense_type;
	private UFDouble amount;
	private Integer price_type;
	private UFDateTime ts;
	private UFDouble price;
	private Integer valuation_type;
	private String rate_id;
	private UFBoolean system_create;
	private String def10;
	private String def2;
	private String def1;
	private String def4;
	private String def3;
	private String def9;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private UFDouble def11;
	private UFDouble def12;
	private UFDouble contract_amount;
	
	private UFDouble cost;
	private UFDouble contract_cost;
	private String bill_value;
	
	public String getBill_value() {
		return bill_value;
	}

	public void setBill_value(String bill_value) {
		this.bill_value = bill_value;
	}

	// 20141129 冗余字段 合同明细在生成应收明细时只返回应收明细的vo，这里同时将合同明细的税种、税率设置到明细行，方面后面进行计算
	@NotDBField
	private Integer tax_cat;
	@NotDBField
	private UFDouble tax_rate;

	// 2015-06-04 冗余字段，车型吨位算法生成费用明细后，设置车型以及车数
	@NotDBField
	private UFDouble car_weight;// 吨位
	@NotDBField
	private Integer carnum;// 车数

	// 2015-06-08
	private String pk_contract_b;// 合同明细号

	
	public UFDouble getCost() {
		return cost;
	}

	public void setCost(UFDouble cost) {
		this.cost = cost;
	}

	public UFDouble getContract_cost() {
		return contract_cost;
	}

	public void setContract_cost(UFDouble contract_cost) {
		this.contract_cost = contract_cost;
	}

	public UFDouble getContract_amount() {
		return contract_amount;
	}

	public void setContract_amount(UFDouble contract_amount) {
		this.contract_amount = contract_amount;
	}

	public Integer getTax_cat() {
		return tax_cat;
	}

	public void setTax_cat(Integer tax_cat) {
		this.tax_cat = tax_cat;
	}

	public UFDouble getTax_rate() {
		return tax_rate;
	}

	public void setTax_rate(UFDouble tax_rate) {
		this.tax_rate = tax_rate;
	}

	public UFDouble getCar_weight() {
		return car_weight;
	}

	public void setCar_weight(UFDouble car_weight) {
		this.car_weight = car_weight;
	}

	public Integer getCarnum() {
		return carnum;
	}

	public void setCarnum(Integer carnum) {
		this.carnum = carnum;
	}

	public String getPk_contract_b() {
		return pk_contract_b;
	}

	public void setPk_contract_b(String pk_contract_b) {
		this.pk_contract_b = pk_contract_b;
	}

	public UFDouble getDef11() {
		return def11;
	}

	public void setDef11(UFDouble def11) {
		this.def11 = def11;
	}

	public UFDouble getDef12() {
		return def12;
	}

	public void setDef12(UFDouble def12) {
		this.def12 = def12;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public static final String PK_RECEIVE_DETAIL = "pk_receive_detail";
	public static final String PK_RECE_DETAIL_B = "pk_rece_detail_b";
	public static final String MEMO = "memo";
	public static final String QUOTE_TYPE = "quote_type";
	public static final String PK_EXPENSE_TYPE = "pk_expense_type";
	public static final String AMOUNT = "amount";
	public static final String PRICE_TYPE = "price_type";
	public static final String PRICE = "price";
	public static final String VALUATION_TYPE = "valuation_type";
	public static final String RATE_ID = "rate_id";
	public static final String SYSTEM_CREATE = "system_create";
	public static final String CONTRACT_AMOUNT = "contract_amount";

	public String getPk_receive_detail() {
		return pk_receive_detail;
	}

	public void setPk_receive_detail(String pk_receive_detail) {
		this.pk_receive_detail = pk_receive_detail;
	}

	public Integer getValuation_type() {
		return valuation_type;
	}

	public void setValuation_type(Integer valuation_type) {
		this.valuation_type = valuation_type;
	}

	public String getPk_rece_detail_b() {
		return pk_rece_detail_b;
	}

	public void setPk_rece_detail_b(String pk_rece_detail_b) {
		this.pk_rece_detail_b = pk_rece_detail_b;
	}

	/**
	 * 属性memo的Getter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * 属性memo的Setter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @param newMemo
	 *            String
	 */
	public void setMemo(String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * 属性quote_type的Getter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @return Integer
	 */
	public Integer getQuote_type() {
		return quote_type;
	}

	/**
	 * 属性quote_type的Setter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @param newQuote_type
	 *            Integer
	 */
	public void setQuote_type(Integer newQuote_type) {
		this.quote_type = newQuote_type;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	public String getPk_expense_type() {
		return pk_expense_type;
	}

	public void setPk_expense_type(String pk_expense_type) {
		this.pk_expense_type = pk_expense_type;
	}

	/**
	 * 属性amount的Getter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @return UFDouble
	 */
	public UFDouble getAmount() {
		return amount;
	}

	/**
	 * 属性amount的Setter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @param newAmount
	 *            UFDouble
	 */
	public void setAmount(UFDouble newAmount) {
		this.amount = newAmount;
	}

	/**
	 * 属性price_type的Getter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @return Integer
	 */
	public Integer getPrice_type() {
		return price_type;
	}

	/**
	 * 属性price_type的Setter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @param newPrice_type
	 *            Integer
	 */
	public void setPrice_type(Integer newPrice_type) {
		this.price_type = newPrice_type;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * 属性price的Getter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPrice() {
		return price;
	}

	/**
	 * 属性price的Setter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @param newPrice
	 *            UFDouble
	 */
	public void setPrice(UFDouble newPrice) {
		this.price = newPrice;
	}

	/**
	 * 属性system_create的Getter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getSystem_create() {
		return system_create;
	}

	/**
	 * 属性system_create的Setter方法. 创建日期:2012-08-09 23:48:22
	 * 
	 * @param newSystem_create
	 *            UFBoolean
	 */
	public void setSystem_create(UFBoolean newSystem_create) {
		this.system_create = newSystem_create;
	}

	public String getRate_id() {
		return rate_id;
	}

	public void setRate_id(String rate_id) {
		this.rate_id = rate_id;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-08-09 23:48:22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_receive_detail";
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-08-09 23:48:22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_rece_detail_b";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-08-09 23:48:22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ts_rece_detail_b";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-08-09 23:48:22
	 */
	public ReceDetailBVO() {
		super();
	}
}
